### PR TITLE
Improved cipher list.

### PR DESCRIPTION
**Pull request by gsnorton**
I believe this change to Network.c improves the security of the negotiated ciphers by lowering priority of RC4 and excluding legacy SSL2 ciphers as well as those without authentication or encryption.

### CODE REVIEW

**Comment by hanswolff** [comment]
RC4 is considered broken and shouldn't be in that list any more

**Comment by gsnorton** [comment]
I erred on the side of caution that RC4 support was there to support older clients.

**Comment by gsnorton** [comment]
SSL3 support, including RC4, is turned off with another SoftEtherVPN configuration option.

**Comment by moatazelmasry2** [comment]
There is another problem with this PR which is that SoftEther can not currently use colon as a separator. You need to implement that as well otherwise SE can not parse the list

**Comment by moatazelmasry2** [comment]
This PR contains errors. Another PR #343 is much cleaner and solves the cipher suite actually in a nicer manner

**Comment by moatazelmasry2** [comment]
The user does not seem to respond anymore. I'd like to close this PR without merging within the next few days if there is no objection

**Comment by gsnorton** [comment]
I will close the request. I simply wanted to draw attention to the cipher list.

**Pull request closed without merging**
