### PR TITLE
Support Debian package build on aarch64 architecture

### PR DESCRIPTION
**Pull request by Leden**
This adds the code recognizing `aarch64` architecture in `debian/rules`.

### CODE REVIEW

**Comment by dnobori** [comment]
Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

**Comment by Leden** [comment]
Sure, I choose 1st option. I allow to apply the same patch into PacketiX VPN.

**Comment by lingqingfeng** [comment]
Hi, I am  a  newcomer.I want to study the Softether VPN. I have read  the source code on windows,but It's so complex.Can I apply for a  program instruction?Thanks.

**Comment by paskal** [comment]
@Leden, I'm afraid you have to fix something after latest merges.

**Comment by dnobori** [comment]
Thank you so much for your contribution to enrich the SoftEther VPN source code.

Your patch has been merged on the main source-tree of SoftEther VPN.

As a token of our gratitude, your GitHub username has been added on the AUTHORS.TXT file and on the header of the related source file.
Please see: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/AUTHORS.TXT

Thanks again for your contribution.

**Comment by Leden** [comment]
@paskal sure, i'll look into it as soon as i get a free minute.

**Comment by paskal** [comment]
@dnobori, you've mentioned this pull request as merged but didn't merged it actually.

**Comment by Leden** [comment]
@paskal, it is merged, in fact. The code itself seems to be copied onto the master branch manually. It's fine, this PR is not needed anymore. I'll close it.

**Pull request closed without merging**
