### PR TITLE
Fix access violation: correct typing mistake in calling Debug(). 

### PR DESCRIPTION
**Pull request by hiura2023**
Changes proposed in this pull request:
 - Fix the bug below 
           Change sess->ClientOption->BindLocalIP  to &sess->ClientOption->BindLocalIP in ClientConnectGetSocket()
 - Others
 -

### CODE REVIEW

**Comment by chipitsine** [comment]
it changes a behaviour of  "Debug" invocation, while PR title says "Bind outgoing connection..."

**Comment by hiura2023** [comment]
I don't know what you mean.
You mean that you have title naming manner ?

**Comment by chipitsine** [comment]
Yes

**Comment by hiura2023** [comment]
Where is it described ?

**Comment by chipitsine** [comment]
the commit message (and PR title) do not give a clud what kind of bug was fixed.
looking at the code does not help

image

**Comment by hiura2023** [comment]
1. Explanation

General description is in title.
Detail description is in Conversations.

I meant that "Bind outgoing connection to a specific IP address" is functional description.
In other words, function "Bind outgoing connection to a specific IP address" has a bug.
Because around line 6296 are part of "Bind outgoing connection to a specific IP address" function.

Detail is described in "Conversations". 
"Change sess->ClientOption->BindLocalIP to &sess->ClientOption->BindLocalIP in ClientConnectGetSocket()"

I think that the information is sufficient.


3. Questions

2.1 Q1
I think that there is enough information, but you can't understand it ( the reason why we must modify the program) ? 
Please answer yes or no.

2.2 Q2
About your pull request "fix windows build". I don't know the kind of bug.

2.3 Q3
About "temporarily suppress clang warnings on "-Wincompatible-function-point…". It is false.
 
2.4 Q4
Where is naming manner described(defined) for title used by Softether Project ?
I can't find on the internet.

**Comment by ilia-shipitsin** [comment]
just to make it clear. I got your point 

```
Detail is described in "Conversations".
"Change sess->ClientOption->BindLocalIP to &sess->ClientOption->BindLocalIP in ClientConnectGetSocket()"
```

that is linked to commit and linked to PR. some people read only commit messages (well, they CAN read conversations, but sometimes they think "ok, that's commit message, I read it"). it would be nice to move that description to commit message

**Comment by chipitsine** [comment]
just to make it clear. I got your point

```
Detail is described in "Conversations".
"Change sess->ClientOption->BindLocalIP to &sess->ClientOption->BindLocalIP in ClientConnectGetSocket()"
```

that is linked to commit and linked to PR. some people read only commit messages (well, they CAN read conversations, but sometimes they think "ok, that's commit message, I read it"). it would be nice to move that description to commit message

**Comment by hiura2023** [comment]
2.1 
> yes.

Unbelievable !
>commit description is made for unfamiliar people

github is for developers. not for unfamiliar people.

>not clear for other people

github is for developers. not for other people.

Arguments can be passed by address or by value.
In this case, It is incorrect to pass argument by value.
It is correct to pass argument by address.
The reason is that passing by value causes an access violation.
Did you understand ?
If you are a developer, this is common knowledge!


2.2
Your words:
>the commit message (and PR title) do not give a clue what kind of bug was fixed.

Your actions:
>fix windows build

I meant that "windows build" is not kind of bug.
Your words and actions don't match.


2.3 
I meant that description "temporarily suppress clang warnings on "-Wincompatible-function-point…" is not correct. Description is false.
>suppress clang warnings

Warning messages are generated in raw log file. not suppressed. We can check warning messages.
Description should be "suppress clang errors".
Don't write lies.


2.4 
>there're no strict rules. 

There is no point in asserting one's own ideas when there are no rules!
Every person has a different idea.

**Comment by chipitsine** [comment]
sorry, if you would prefer to develop in your own fork, it may be more comfortable for you.
thus you can still develop and you do not have to argue with anybody.

I do not understand your intention here

**Comment by hiura2023** [comment]
Argument must be changed.
This is because other users will be damaged.

I think below.
It would be better for you to issue the pull request and have it merged.

**Comment by chipitsine** [comment]
well, we are on the same page.

if you work in your own fork, you do not have to argue with anybody (maybe, except police and other governmental facilities).
if you contribute to other repo, you communicate with people, they may have concerns. if you are comfortable with that communication, you simply can stop contributing and stay in your own fork.

I'm sorry that you interpret things like we are not following our own rules (I beleive we do). It happens from time to time. It is ok not to contribute in such case.

**Comment by hiura2023** [comment]
Title was changed.

**Comment by hiura2023** [comment]
I have been waiting a long time for you to fix this "access violation".
However, this bug has not been fixed yet.
So I have changed the title to fit your idea.

**Pull request merged**
