### PR TITLE
Fix build error on alpine

### PR DESCRIPTION
**Pull request by weidi**
Changes proposed in this pull request:
 - Changed some imports as discussed in Issue #1439
 - Tested build on alpine and debian and works.

### CODE REVIEW

**Review by chipitsine — COMMENTED** [review]
Should the ifdef Linux end earlier than openbsd? Or they are nested on purpose?

**Comment by weidi** [comment]
> Should the ifdef Linux end earlier than openbsd? Or they are nested on purpose?

You´re right, was playing around too much.

**Comment by weidi** [comment]
Also added a alpine / musl build workflow using github workflows, hope that´s ok otherwise i try to adapt it to azure-pipelines.

**Review by chipitsine — COMMENTED** [review]
Why musl is enabled "on push" only? It will be skipped on pull request that way. Should trigger be adjusted to pull request as well?

`on: [push, pull_request]`

**Comment by chipitsine** [comment]
We are fine with github actions as far as it works.

**Comment by weidi** [comment]
You are absolutely right, now triggered on push an pull_request

**Comment by chipitsine** [comment]
wow, github required my approve to run workflow for the first time.

I approved, let's see how it goes.

**Comment by domosekai** [comment]
This PR shouldn't take 15 commits and please squash them next time.

**Comment by chipitsine** [comment]
I understand that squashing is welcome, I decided not to insist this time

**Comment by weidi** [comment]
Sorry folks, i thought squashing would be done on merging, i did a mistake to make changes on master branch thus i was undable to properly quash on my fork. will do better next time.

**Pull request merged**
