### PR TITLE
Add the possibility to send the Virtual Hub Name to an external DHCP server

### PR DESCRIPTION
**Pull request by yehorov**

### CODE REVIEW

**Comment by dnobori** [comment]
Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

**Comment by yehorov** [comment]
I'm choosing "Option1: Allowing us to apply the same patch into PacketiX VPN".
Thanks.

**Comment by dnobori** [comment]
Thank you so much for your contribution to enrich the SoftEther VPN source code.

Your patch has been merged on the main source-tree of SoftEther VPN.

As a token of our gratitude, your GitHub username has been added on the AUTHORS.TXT file and on the header of the related source file.
Please see: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/AUTHORS.TXT

Thanks again for your contribution.

**Comment by jacac** [comment]
I could not get this to work. Wireshark does not report any option 77 set. Is this only working in a SecureNat environment with an external DHCP Server?

**Comment by yehorov** [comment]
You need to switch the **UseHubNameAsDhcpUserClassOption** on to enable this functionality.

**Comment by jacac** [comment]
Yes, this was enabled and still not getting the user class identifier set. A restart of the service was also performed. 

The AssignVLanIdByRaduisAttribute is also enabled. Could it be that the DHCP traffic is handled differently if VLANS are used?

**Comment by yehorov** [comment]
If you can see DHCP requests and responses in tcpdumps, then VLAN processing doesn't affect DHCP traffic.
Could you show your configuration?

**Comment by jacac** [comment]
Thanks yehorov for looking into this. I had finaly more time to troubleshoot this. Here are my results:

With IPsec I can see the user class defined in the DHCP Discover packet. Using the Softether VPN client Ver 4.25 the user class is not added. 

Is this feature only for IPsec connections?

**Comment by jacac** [comment]
This is the Virtual Hub configuration. As far I remember most of the settings are default except for UseHubNameAsDhcpUserClassOption and radius authentication.

[VPN HUB.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/2443117/VPN.HUB.txt)

**Comment by jacac** [comment]
Upgraded the VPN Manager and see now in the description that it is only available for L2TP/IPsec. Thanks for looking into this.

**Pull request merged**
