### PR TITLE
Update strtable_pt_br.stb with latest translations of main interface

### PR DESCRIPTION
**Pull request by Flucons**
Added basic translations

### CODE REVIEW

**Comment by chipitsine** [comment]
can you please provide some meaningful commit message ?
("update bla-bla-bla..." does not make sense for the people)

**Comment by Flucons** [comment]
> can you please provide some meaningful commit message ?
> ("update bla-bla-bla..." does not make sense for the people)

Sorry, I'm new on Github, but I will improve the messages. In the last commits I am correcting some errors that were preventing file verification (missing parts, quoted errors ...)

I Translated the installer process and main interface to pt-br.

Thanks

**Comment by chipitsine** [comment]
@Flucons , sorry for delay
do you mind to complete your PRs ?

**Comment by Flucons** [comment]
Hello @chipitsine. Sorry, but I didn't understand.
Do you mean to finish translating everything?
For now I don't want to translate anymore. Maybe next year...
I believe the main has been translated.

**Comment by chipitsine** [comment]
no, I mean merge existing PRs

**Comment by Flucons** [comment]
Yes, I want to merge, but how do I do it? I'm not allowed to merge...

**Comment by chipitsine** [comment]
I'm allowed to merge :)

so, generally it is ok. however, it is not very good to use "Updated blah-blah-blah file" commit messages. People will not understand it.

I suggest to combine all changes into singe commit with meaningful commit message like "pt-br translation"

Can you do it ? Or I can use your commits and make new PR (preserving your authorship of course)

**Comment by Flucons** [comment]
Hi, the second option seems better to me and so you can do it the right way. Use my commits and make a new PR.

Thanks for your attention.

**Comment by chipitsine** [comment]
closed in favour of https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1057

**Pull request closed without merging**
