### PR TITLE
CMake: add support for RPM packaging with CPack

### PR DESCRIPTION
**Pull request by davidebeatrici**
Changes proposed in this pull request:
 - Add support for RPM packaging with CPack
 - Remove `centos` directory

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by chipitsine** [comment]
I tend to explicit define (by user) which package has to be built, deb or rpm

determine "rpmbuild" is tricky. it might be CentOS with no rpmbuild installed, for example.

**Comment by davidebeatrici** [comment]
I agree.

**Comment by chipitsine** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/302 is superseeded by #648 ?

**Comment by davidebeatrici** [comment]
Yes.

**Comment by chipitsine** [comment]
I'll to build rpm on fedora

**Comment by chipitsine** [comment]
should we drop standalone "systemd" scripts (even with https://github.com/SoftEtherVPN/SoftEtherVPN/pull/454) in favour of CPack ?

**Comment by davidebeatrici** [comment]
No, we have to copy them manually as CPack doesn't support them.

**Comment by chipitsine** [comment]
I built rpm, it's missing startup script (either systemd or /etc/rc.d)

**Comment by davidebeatrici** [comment]
It's missing also in the DEB packages.

**Comment by chipitsine** [comment]
it should be fixed at least when we will host those RPM somewhere

**Comment by davidebeatrici** [comment]
Indeed.

**Pull request merged**
