### PR TITLE
Add 'stbcheck': the STB File Multilanguage Full-Mesh Consistency Checker

### PR DESCRIPTION
**Pull request by dnobori**
Changes proposed in this pull request:
 - Adds 'stbcheck': the STB File Multilanguage Full-Mesh Consistency Checker.

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

1

-

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by chipitsine** [comment]
if nobody minds, I'll add that to app veyor

**Comment by dnobori** [comment]
That is a good idea if it supports .NET Core 2.1.

**Comment by chipitsine** [comment]
yes, I noticed "dotnet run"

I'll check that

**Comment by chipitsine** [comment]
small note, as for ".gitignore", shall we move all things to the main ".gitignore" ?

**Comment by dnobori** [comment]
That is no problem. Could you perform it if possible please?

**Comment by davidebeatrici** [comment]
Done.

I also squashed the commits and replaced the spaces with tabs (they were mixed).

**Comment by dnobori** [comment]
Thank you.
I also improved .gitignore not to affect this change to the entire SoftEtherVPN repository.
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/709/commits/8c2e0f32d366cb17c4af4d2ffecb4061f8d302b9


The Visual Studio-related .gitignore I added on this commit is intended only to apply on the `tools/stbchecker' directory.

**Comment by davidebeatrici** [comment]
You're welcome.

Please squash the commits once the pull request is complete.

**Comment by dnobori** [comment]
Also I changed the directory name `tools/` to `developer_tools/` in order to make it clear that these tools in the directory are just for developers, not for users. I prefer further development-time tools should be placed on this `developer_tools/` directory.

**Comment by davidebeatrici** [comment]
No problem.

**Comment by dnobori** [comment]
Could you tell me how to *squash the commits* please? I pushed the 'combine commits' menu on TortoiseGit and the commit ID https://github.com/SoftEtherVPN/SoftEtherVPN/pull/709/commits/b4d42d9cc3a231e08c6da88e09d93df4f82ddec5 is created. Is it ok?

image

**Comment by davidebeatrici** [comment]
Highlight the commits, right click on one of them, choose `Combine to one commit`.

**Comment by davidebeatrici** [comment]
The merge commit is created because Git doesn't rebase by default.

I recommend to enable the automatic rebase setting:
`git config --global pull.rebase true`

**Pull request merged**
