### PR TITLE
Fix "Not on NT" error message and add uihelp to vpncmd

### PR DESCRIPTION
**Pull request by siddharth-narayan**
Fixes https://github.com/SoftEtherVPN/SoftEtherVPN/issues/2031

Running vpnclient.exe fails because ```ms->IsNt``` is never set to true. This seems to be old code from the stable branch that was never changed to ```IsNt()```.

This pull request changes changes ```ms->IsNt``` to ```IsNt()```, and removes ```IsNt``` from the ```MS``` struct, because it is no longer necessary.

### CODE REVIEW

**Comment by siddharth-narayan** [comment]
I've added the fix for the NicCreate error code 31 that I mentioned briefly in the issue. The problem was that vpncmgr.exe starts up a ui helper using the /uihelp argument which handles some functions that it should not be handling. I think vpnclient.exe should be adding in the vlan itself instead of delegating the task to the uihelp process. It doesn't really make sense and seems like bad practice to have the gui doing things that the backend should be able to do. Fixing that issue requires fixing the entire client notification system, so instead I just added the uihelp process to vpncmd.exe as well.

**Comment by chipitsine** [comment]
Thanks, I'm going to have a look soon

**Comment by siddharth-narayan** [comment]
Is there any update?

**Comment by chipitsine** [comment]
not yet. sorry
hopefully this week

**Comment by siddharth-narayan** [comment]
No problem, I don't mind :)

**Comment by chipitsine** [comment]
sorry for delay.
thank you for contribution!

**Pull request merged**
