### PR TITLE
Fix hamcore access: Correcting path separator for hamcore.

### PR DESCRIPTION
**Pull request by hiura2023**
Changes proposed in this pull request:
 - VPN Server can not install the drivers below due to the incorrect path separator
   	C:\Windows\System32\drivers\pxwfp.sys
	C:\Windows\System32\drivers\SeLow_x64.sys
 - How to reproduce
   ①stop VPN Server
   ②stop service
             sc stop    pxwfp
             sc stop    selow
   ③delete the driver if it exists.
             delete C:\Windows\System32\drivers\pxwfp.sys
	     delete C:\Windows\System32\drivers\SeLow_x64.sys
   ④run VPN Server
   ⑤confirm that IPSEC and local bridge function do not work.

 - Change the path separator from \ to / for hamcore access
    IPSEC and local bridge function will work.

Refer to
https://www.vpnusers.com/viewtopic.php?f=7&t=68333&p=99266

### CODE REVIEW

**Comment by chipitsine** [comment]
thank you for contribution.

do you have maybe an idea how to check that automatically during CI/CD ?
(as a separate PR, I do not want to block contribution)

**Comment by chipitsine** [comment]
@hiura2023 , I checked stable edition and I do not see similar fix in it

https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/master/src/Mayaqua/FileIO.c#L2916

can you please verify whether that bug applies to stable branch as well ? if so, we'll ask Daiyuu Nobori to apply to stable branch also

**Comment by davidebeatrici** [comment]
This does not apply to the stable version because it does not rely on libhamcore.

**Comment by hiura2023** [comment]
> @hiura2023 , I checked stable edition and I do not see similar fix in it
> 
> https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/blob/master/src/Mayaqua/FileIO.c#L2916
> 
> can you please verify whether that bug applies to stable branch as well ? if so, we'll ask Daiyuu Nobori to apply to stable branch also

My VPN Server works fine.

My environment
SE:VPN Server of VPN4.0 (VER4.38, BUILD 9760)
OS:Win11


- ### As to the hamcore archive specification
Path separator is diffrent between two editions.

Stable Edition:
The path separator of "hamcore.se2" for VPN4.0 (VER4.38, BUILD 9760) is \ .

Developer Edition:
The path separator of "hamcore.se2" for VPN5.02 is /.

You can check the separator of "hamcore.se2" using editor notepad.

Maybe developer made a mistake in trying to change the path separator from \ to /.

**Comment by davidebeatrici** [comment]
It is indeed a mistake. The idea was to use `/` on all platforms, for consistency, but unfortunately a few paths were missed when accounting for the change.

#1351

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Comment by hiura2023** [comment]
> do you have maybe an idea how to check that automatically during CI/CD ?

No, I haven't.
I need to learn more about CI/CD.

**Comment by chipitsine** [comment]
@hiura2023 , I decided to make a release with your fix https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/5.02.5182

there are several issues which looks to be resolved by your patch, we'll ask them to try new release

**Comment by hiura2023** [comment]
Thank you for letting us know what action you intend to take.

**Pull request merged**
