### PR TITLE
Bind outgoing connection to a specific IP address

### PR DESCRIPTION
**Pull request by hiura2023**
Changes proposed in this pull request:
 - To bind individual outgoing connection (cascade or VPN connection) to a specific IP address.
 - Add the input field on the screen of advanced settings.
 - Add the function to bind the socket to a specific IP address.

CLT_VPNCON_ADV_2023-06-29
SRV_CASCON_ADV_2023-06-29
[CONFIG_OUTGOINGCON_2023-06-29.JPG.TXT](https://github.com/SoftEtherVPN/SoftEtherVPN/files/11901060/CONFIG_OUTGOINGCON_2023-06-29.JPG.TXT)

### CODE REVIEW

**Comment by hiura2023** [comment]
General description of changes

1. Make 2nd and subsequent TCP/IP connection use the same IP address assigned for the 1st TCP/IP connection by OS.
① When the 1st TCP/IP connection is established, save the local IP address assigned by OS for the 1st TCP connection.
② When trying to establish connection for 2nd and subsequent TCP/IP connection, bind the socket to the same IP address assigned for the 1st TCP/IP connection by OS.

2. Enable to bind 1st TCP/IP connection to a specific IP address.
   When "No Adjustment of Routing Table" is checked, processing below applies to the 1st TCP/IP connection.
① If specified IP address is zero, do nothing. 
② If specified IP address is nonzero, bind the socket to the specified IP address.

3. These changes
① Enable to have VPN tunnel created on physical network.
    In the case of multiple VPN connections, VPN tunnel is created under VPN tunnel with current edition.
② Enable to select an IP address from multiple IP addreses assigned to single network adapter.
    The user wants to have this function. 
    https://www.vpnusers.com/viewtopic.php?f=15&t=68268

**Comment by Evengard** [comment]
Shouldn't that be bound to the device name instead of IP?

**Comment by davidebeatrici** [comment]
It's useful especially when using dynamic address(es), but a network interface can have multiple at the same time in any case.

Ideally we should support both device name and IP address specification.

**Comment by domosekai** [comment]
First of all, the code suggested is not in line with SoftEther style.
Second, binding subsequent connections to the same source IP would break things especially in IPv6 environment. This should not be enabled by default.

**Comment by hiura2023** [comment]
First, What is "SoftEther style" ?
Where is the "SoftEther style" described ?
 
As for second.
What does "break things" means ?
Did you set the correct IP address as source IP address ?
Even if you set the incorrect IP address, bind processing completes successfully. But connect processing fails.

Incorrect IP address means that no route to destination is available with the specified IP address.
Correct IP address means that route to destination is available with the specified IP address.

Anyway detail information needed.

**Comment by hiura2023** [comment]
Changes proposed in this pull request:
In addition to Source IP Address, user can specify Source Port No. to bind.

To bind individual outgoing connection (cascade or VPN connection) to a specific Source IP address **& Source Port No.**
Add the input field for **Source Port No.** on the advanced settings screen.
Add the function to bind the socket to a specific **Source Port No.**

[2023-08-07_CLI_IPCONFIG_OUTGOING.TXT](https://github.com/SoftEtherVPN/SoftEtherVPN/files/12289830/2023-08-07_CLI_IPCONFIG_OUTGOING.TXT)
[2023-08-07_CLI_VPNCONFIG_OUTGOING.TXT](https://github.com/SoftEtherVPN/SoftEtherVPN/files/12289835/2023-08-07_CLI_VPNCONFIG_OUTGOING.TXT)
2023-08-07_CLT_VPNCON2_OUTGOING
2023-08-07_CLT_VPNCON3_OUTGOING
2023-08-07_CLT_VPNCON5_OUTGOING

**Comment by hiura2023** [comment]
Who is in charge of approval for this pull request ?
I am waiting for a long time.

**Comment by chipitsine** [comment]
sorry for delay. I'll have a look

**Comment by hiura2023** [comment]
How long will it take to approve ?

**Comment by chipitsine** [comment]
I am going to have a look next weekend

**Comment by chipitsine** [comment]
@hiura2023 , please add missing localizating strings (if there are no strings, english seem to be good)

https://github.com/SoftEtherVPN/SoftEtherVPN/actions/runs/6137977316/job/16654377512

locally check can be run as

```
          cd developer_tools/stbchecker
          dotnet run ../../src/bin/hamcore
```

**Comment by chipitsine** [comment]
@hiura2023 , can you have a look ? (we run Coverity scan daily on master branch)

```
** CID 400236:  Memory - illegal accesses  (RETURN_LOCAL)
/src/Mayaqua/Network.c: 14647 in BindConnectThreadForIPv6()


________________________________________________________________________________________________________
*** CID 400236:  Memory - illegal accesses  (RETURN_LOCAL)
/src/Mayaqua/Network.c: 14647 in BindConnectThreadForIPv6()
14641     
14642                   // Top of Bind outgoing connection
14643                   if (s != INVALID_SOCKET){
14644                           int ier;
14645                           IP tmpIP;
14646     
>>>     CID 400236:  Memory - illegal accesses  (RETURN_LOCAL)
>>>     Using "p->LocalIP", which points to an out-of-scope variable "tmpIP".
14647                           if (p->LocalIP == BIND_LOCALIP_NULL) {
14648                                   StrToIP(&tmpIP, "0::0");        // A NULL address for the argument "p->LocalIP" is treated as if "0::0" in IPV6 was specified.
14649                                   p->LocalIP = &tmpIP;
14650                           }
14651     
14652                           if ((IsZeroIP(p->LocalIP) == false) || (p->LocalPort != 0)){

```

**Comment by hiura2023** [comment]
To @chipitsine.

Thank you for accepting my pull request.

Variable "p->LocalIP" may be NULL address.
If it is NULL,  "0::0" must be used by bind_sock() function.
I defined the local variable "tmpIP" for "0::0". 
I don't know the reason why it is out-of scope.

**Comment by chipitsine** [comment]
" &tmpIP" is a reference to local variable. it is not available outside scope

**Comment by chipitsine** [comment]
as long as " p->LocalIP = &tmpIP;" is not being returned from function, it looks good

**Comment by chipitsine** [comment]
please send new PR on that. as for "BindConnectTimeoutIPv4", I do not see any "&" applied to local variable out of function scope.

I suspect that is already fixed in the snippet above, but it is hard to compare that way without PR

**Comment by hiura2023** [comment]
To @chipitsine,

Thank you for adding missing localization.

**Pull request merged**
