### PR TITLE
fix nullptr deref

### PR DESCRIPTION
**Pull request by chipitsine**
partially merge https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1921

@icy17  ?

### CODE REVIEW

**Comment by chipitsine** [comment]
@metalefty , can you please have a look at cirrus-ci part ?

according to my observation, it picks system ssl lib (but headers from /usr/local): `libssl.so.111 => /usr/lib/libssl.so.111 (0x12ba15d3c000)`

I wonder how it worked earlier, I see no changes in cirrus-ci or cmake. also, I'm not sure what would be the proper fix (maybe something from freebsd ports ?)

**Comment by metalefty** [comment]
Okay, let me time.

**Comment by metalefty** [comment]
The CI on this PR looks fine. Is there still anything I should have a look?

**Comment by ilia-shipitsin** [comment]
I'm not sure why openssl31 did not run for this PR.
here's link: https://cirrus-ci.com/task/5524575400755200

**Comment by chipitsine** [comment]
I'm not sure why openssl31 did not run for this PR.
here's link: https://cirrus-ci.com/task/5524575400755200

**Comment by metalefty** [comment]
I have not reproduced that failure on my FreeBSD box. Still looking into that.

**Comment by chipitsine** [comment]
@metalefty , I've an idea that `find_package(OpenSSL REQUIRED)` somehow cannot detect openssl package named as `openssl31`

**Pull request merged**
