### PR TITLE
change ./configure to cmake .

### PR DESCRIPTION
**Pull request by scegg**
Changes proposed in this pull request:
 - change ./configure to cmake .

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

-

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by chipitsine** [comment]
@davidebeatrici , I'm going to merge it

**Comment by davidebeatrici** [comment]
We should use a temporary folder for CMake, as we do with `configure`:

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/879dc8f6b8daa017ebbe843a57fd15ebb36877c3/configure#L20-L28

**Comment by chipitsine** [comment]
well, this PR does make documentation better
so, I'm merging it

as the @scegg keeps silence, so we'll add things mentioned by @davidebeatrici in future PRs :)

**Comment by scegg** [comment]
> well, this PR does make documentation better
> so, I'm merging it
> 
> as the @scegg keeps silence, so we'll add things mentioned by @davidebeatrici in future PRs :)

Sorry. I didn't get any notification about this...
Glad to see that's resolved.

**Pull request merged**
