### PR TITLE
add missing localization

### PR DESCRIPTION
**Pull request by chipitsine**
this is a follow up of
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1867

English localization is added for now

@hiura2023

### CODE REVIEW

**Comment by metalefty** [comment]
Missing translations can be checked by CI?

**Comment by chipitsine** [comment]
We started that recently

**Comment by hiura2023** [comment]
I can't get installer of "Softether VPN" from azure.

Errors are found in azure pipelines.
https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build?definitionId=6

**Comment by chipitsine** [comment]
yep. please try this build https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1905

**Pull request merged**
