### PR TITLE
initial travis-ci support

### PR DESCRIPTION
**Pull request by chipitsine**
Changes proposed in this pull request:
 - support for CI (https://travis-ci.org)

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- one

### CODE REVIEW

**Comment by paulmenzel** [comment]
Could you please improve the commit message? A statement as the commit message summary would be nice, and also a better description, why certain options were chosen.

If you don’t mind, could you please update the merge/pull request to use the commits in my branch *integrate-travis-ci* [1]? I amended your commit. I’d also vote for squashing the two clean-up commits into your commit, which of course retains your name as the author.

```
$ git remote add paulmenzel https://github.com/paulmenzel/SoftEtherVPN
$ git fetch paulmenzel
$ git checkout travis-ci
$ git reset --hard paulmenzel/integrate-travis-ci
```

I’ll still need to improve the “version output commit”, but you can check the result [2].

[1] https://github.com/paulmenzel/SoftEtherVPN/tree/integrate-travis-ci
[2] https://travis-ci.org/paulmenzel/SoftEtherVPN/builds/282365686

**Comment by chipitsine** [comment]
@paulmenzel , I'll have a look.
actually, I would start with some small matrix.

there's openssl-1.1.0 on the go, so at least we need to define "openssl version" variable.
(and probably, some openssl build procedure, i.e. build certain openssl version from source ... and cache it)

I'm not sure, that we need such a wide matrix as yours.
anyway, I'll have a look

**Comment by moatazelmasry2** [comment]
@paulmenzel I could not find a PR with your code. 

I'd like to work with you guys on creating the first travis-ci for this project.

**Comment by chipitsine** [comment]
@moatazelmasry2 

currently, there's no unit test, I mean at all. it is bad.
I hope that even initial travis-ci support will encourage people to write tests.

as for github releases, I think there'll be more luck with app veyor

can you merge my PR (and people will expand build matrix in the ongoing commits) ?
I'm going to add something like "specify openssl version. ... build it ... ok, now we can build against 1.0.2 and 1.1.0..."

**Comment by paulmenzel** [comment]
@moatazelmasry2, do you want me to create one? Currently there is only [the branch *integrate-travis-ci* in my repository](https://github.com/paulmenzel/SoftEtherVPN/commits/integrate-travis-ci)'

@chipitsine, could you please improve the commit messages and commit descriptions as I asked?

**Comment by chipitsine** [comment]
commit message is "initial travis-ci support" which precisely describe PR.
can you please be more detailed on what is wrong with commit message ?

**Comment by paulmenzel** [comment]
@chipitsine, please look at the commit in my branch. So, please use statements, and elaborate. You set certain options, which are not needed in my opinion. That’s what a commit message is for, elaborate why you chose the small matrix and chose certain options.

**Comment by chipitsine** [comment]
I do not agree with your PR, it is overcomplicated from my point of view. However, you can make your own PR.  I made my own PR which I am happy about.
if there's something wrong with commit message, please be more detailed

**Comment by paulmenzel** [comment]
@chipitsine, understood. I thought, we can work together, but apparently not. And you didn’t even look at my branch and read my comment. Here it is again how [I amended your commit message](https://github.com/paulmenzel/SoftEtherVPN/commit/7445cdcc9fcd89048cf10c96f78d367a84f467a5):

> travis: Add configuration file for Travis CI
>
> Integrate [Travis CI][1] into SoftEther VPN. Follow the [Travis CI
> documentation][2] for a C project.
>
> Right now, the configured virtualization environment includes GCC 4.8.4
> and Clang 3.5.0.
>
> ```
> $ gcc --version
> gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
> […]
> $ clang --version
> clang version 3.5.0 (tags/RELEASE_350/final)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> ```
>
> Quite a lot of warnings are thrown. Later, this can be extended to use
> different versions of the compilers to find issues.
>
> [1]: https://travis-ci.org/
> [2]: https://docs.travis-ci.com/user/languages/c/

With your commit message with just the summary, people not knowing Travis CI have no idea what it is about, and do not even know how to set it up.

**Comment by paulmenzel** [comment]
And it’s not clear why you do not go with GCC 7 with better and more elaborate warning and the old version 4.8.4.

**Comment by chipitsine** [comment]
@paulmenzel , I do not insist on gcc-4.8.4, from my point of view it makes some sense to test in "the most popular environments", something like running "centos6,7 ... ubuntu 16.04 ....debian 8,9" in docker and use compilers provided with certain distributive.

from this point of view, both 4.8.4 and 7.X do not make a lot of sense because ubuntu trusty is pretty outdated.

as I said earlier, I'd leave "matrix expansion" to other collaborators :) as soon as it is merged, there'll be some buzz around it, stay tuned :)

**Comment by paulmenzel** [comment]
And your opinion/reasoning is totally fine, so please add it to the commit message, where that belongs and not in some merge/pull request discussion.

**Comment by moatazelmasry2** [comment]
I'm also in favor of first committing something very simple at the beginning and hopefully more commits to follow. @SoftEtherVPN/softether-development-board-members  Please upvote so we can merge this

**Comment by moatazelmasry2** [comment]
Thank you so much for your contribution to enrich the SoftEther VPN source code.

Your patch has been merged on the main source-tree of SoftEther VPN.

As a token of our gratitude, your GitHub username will be added on the AUTHORS.TXT file. (It will be done within a few days.)
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/AUTHORS.TXT

Thanks again for your contribution.

**Comment by chipitsine** [comment]
@moatazelmasry2 , can you also enable this repo on https://travis-ci.org ?

**Comment by moatazelmasry2** [comment]
I will contact Daiyuu to do that because I don't have enough admin rights

**Pull request merged**
