### PR TITLE
Make config(db), log, pid directory customizable

### PR DESCRIPTION
**Pull request by metalefty**
## Background
SoftEtherVPN writes config, log, pid files in the same directory with executables (vpnserver, vpnbridge, vpnclient). This is reasonable when using SoftEtherVPN as pre-built binary tarball. However, this is incompatible with most Linux/BSD distributions. This incompatibility is one of the big reason that very few Linux/BSD distributions provide SoftEtherVPN as package. Some times executable directories such as `/usr/bin` or `/usr/libexec` are read-only or protected for security.

In most distro `/var/log` is the standard place to put logs, `/var/run` or `/run` is the place for PID files, and `/var/db` or `/var/lib` would be the best place to put persistent data modified by programs as they run.

I made this PR especially for distro package maintainers.

## How to override config, log, pid directories

Set `SE_DBDIR`, `SE_LOGDIR`, `SE_PIDDIR` in cmake. I carefully implemented this and if these variable are not specified, it behaves same as before. **Default behaviour is not changed at all**.

```
cmake -DSE_PIDDIR=/tmp/var/run/softether -DSE_DBDIR=/tmp/var/db/softether -DSE_LOGDIR=/tmp/var/log/softether ..
```

## How it works

Files created by SoftEtherVPN will be like this:
```
cd /tmp; find var
var
var/run
var/run/softether
var/run/softether/.VPN-ED5B974492
var/run/softether/.pid_B76AC4F492D0924947323EAE07003786
var/run/softether/.ctl_B76AC4F492D0924947323EAE07003786
var/log
var/log/softether
var/log/softether/security_log
var/log/softether/security_log/DEFAULT
var/log/softether/security_log/DEFAULT/sec_20191204.log
var/log/softether/server_log
var/log/softether/server_log/vpn_20191204.log
var/log/softether/packet_log
var/db
var/db/softether
var/db/softether/chain_certs
var/db/softether/backup.vpn_server.config
var/db/softether/backup.vpn_server.config/00000000_vpn_server.config
var/db/softether/lang.config
var/db/softether/vpn_server.config
```

As far as I tested, `LogFileList` command also works properly.
```
VPN Server>logfilelist
LogFileList command - Get List of Log Files
Getting list of log files. This may take a while. Please wait...

In total there are 3 log files.
Item         |Value
-------------+-------------------------------------
Log File Name|security_log/DEFAULT/sec_20191204.log
File Size    |76 Bytes
Updated on   |2019-12-04 23:38:16
Location     |softether.example.com
-------------+-------------------------------------
Log File Name|server_log/vpn_20191204.log
File Size    |3.78 KBytes
Updated on   |2019-12-04 23:38:21
Location     |softether.example.com
-------------+-------------------------------------
Log File Name|server_log/vpn_20191205.log
File Size    |1.28 KBytes
Updated on   |2019-12-05 00:00:36
Location     |softether.example.com
The command completed successfully.

VPN Server>
```

Some special config files such as `adminip.txt`, `private_ip.txt` or `custom.ini` should be put in `SE_DBDIR`, then it should work. Also intermediate certificates should be put in `${SE_DBDIR}/chain_certs`.

`SE_DBDIR`, `SE_LOGDIR`, `SE_PIDDIR` directories must be created before running SoftEtherVPN. SoftEtherVPN doesn't create them.

## Conclusion

This changes are based on my work on FreeBSD Ports Collection. To reduce ports local patches as much as possible, I'm pushing this to upstream.  I believe this change will enable Linux/BSD distro to provide SoftEtherVPN as package and it helps to spread SoftEtherVPN.

### CODE REVIEW

**Comment by chipitsine** [comment]
btw, @metalefty , can you have a look at ... our cirrus-ci scripts ?

seem, we do not run `./vpncmd /tool /cmd:Check` and we do not catch errors like https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1045

**Comment by chipitsine** [comment]
also, we use 12.0 image

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.cirrus.yml#L3

I'm not sure, maybe we need to review that (for example add 11.X as well)

**Comment by metalefty** [comment]
Okay, actually I've never used Cirrus CI but I'll have a look.

**Comment by Andy2244** [comment]
Quick question, i assume this does not affect #575 ?

**Comment by metalefty** [comment]
This changes where to save logs, pid files, and configuration files. No other things are changed.

**Pull request merged**
