### PR TITLE
Fix Virtual DHCP Server: Correct DHCP Sequence

### PR DESCRIPTION
**Pull request by hiura2023**
Changes proposed in this pull request:
 - Virtual DHCP sequence is not correct.
   Why does DHCP NAK respond to DHCP DISCOVER ?
 - Change DHCP sequence like below.
 - Actual action
①DHCP DISCOVER
②DHCP NAK
③DHCP DISCOVER
④DHCP NAK
⑤Sequence ③,④ repeated several times.
⑥DHCP DISCOVER
⑦DHCP OFFER
⑧DHCP REQUEST
⑨DHCP ACK
Attached A and B

 - Expected action
①DHCP DISCOVER first
②DHCP DISCOVER second
③DHCP DISCOVER repeated several times 
④DHCP OFFER
⑤DHCP REQUEST
⑥DHCP ACK
DHCP client resend ②,③ if VPN server is not ready to reply ④ immediately
Refer to RFC2131

 -  Ideal action
①DHCP DISCOVER
②DHCP OFFER
③DHCP REQUEST
④DHCP ACK

Refer to RFC2131:
https://www.rfc-editor.org/rfc/rfc2131#section-4.4
 [Page 34]Figure 5:  State-transition diagram for DHCP clients

Timeout example:
https://www.cente.jp/files/20100222_TCPIPv4_001-0016.pdf

Attached A:
The time-out period is 20 seconds on "security policy of user" screen.
DHCP_ACTUAL_20SEC2024-04-29

Attached B:
[SEVPN_DHCP_TOO_LATE_REMOTE.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/15160522/SEVPN_DHCP_TOO_LATE_REMOTE.txt)

### CODE REVIEW

**Comment by chipitsine** [comment]
How do you find all those ? Just curious

**Comment by hiura2023** [comment]
I updated first comment.

I think that DHCP_NAK responds to DHCP_REQUEST, not DHCP_DISCOVER.
Who added virtual DHCP server ? Ask him.

**Comment by hiura2023** [comment]
>How do you find all those ? Just curious

I added the test environment and test result later.
find what ?

**Comment by chipitsine** [comment]
> > How do you find all those ? Just curious
> 
> I added the test environment and test result later. find what ?

I've some ideas on automated testing.

in theory we can try ISC dhclient, which is flexible and allows dhclient-script to handle response instead of applying to system live. but those are ideas for future improvements

**Comment by hiura2023** [comment]
### Description of second pull request I added

1. Renewal lease time function does not work. 
2. I changed the DHCP renewal lease time function to work.
3. Refer to  https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1947

### Ideal action
①DHCP DISCOVER
②DHCP OFFER
③DHCP REQUEST
④DHCP ACK
⑤DHCP REQUEST  FOR RENEWAL LEASE TIME #1
⑥DHCP ACK
⑦DHCP REQUEST  FOR RENEWAL LEASE TIME #2
⑧DHCP ACK
⑨DHCP REQUEST  FOR RENEWAL LEASE TIME #3
⑩DHCP ACK
CONTINUED

Attached A:
DHCP_REQ_RENEWAL_20SEC2024-05-03

**Comment by PizzaProgram** [comment]
@hiura2023  Excellent work!  
  
I've checked the code changes and as much as I understood it's perfect!  
_(I'm not a C expert, only Delphi but your coding is very nice and understandable. Special thanks for the inserted comments! )_  
  
If this Commit will be applied,  
 - FIXed IPs MUST be outside of the normal DHCP range. Right ?  
  
_Anyway, shouldn't be this commit applied to the Developer Edition too? Maybe it would be accepted faster there to test ..._

**Comment by chipitsine** [comment]
thank you for contribution!

**Comment by chipitsine** [comment]
I'm going to make a release today

**Pull request merged**
