### PR TITLE
musl support

### PR DESCRIPTION
**Pull request by thepyper**
As previous discussion on my previous pull request, I implemented musl support (which is a small change in Internat.c file) using conditional compilation, so that default behaviour is unchanged, and using a new environment variable allows musl compilation to work.

Summary of previous discussion:
- musl has a bug in iconv() function, which cause softether to compile correctly, but exhibit a bad runtime behaviour: any string conversion fails because iconv initialization fails early;
- to correct this bug, I used the same workaround that was already used to compile on macOS, see Internat.c diff and this is self-evident;
- workaround is triggered compile-time by the UNIX_LINUX_MUSL #define flag;
- cmake has been modified to add the -DUNIX_LINUX_MUSL command line flag to gcc when the environment variable USE_MUSL is set to YES

So, build on musl with that commands:

export USE_MUSL=YES
./configure
make -C tmp

I have tested this patch on alpine linux and produces working executables.

About vpn patch acceptance, for me option 1 is ok.

Is this PR ok for anybody?
Thanks!

Davide

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

-

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by chipitsine** [comment]
after travis-ci is fixed, I do not mind to merge it

**Comment by thepyper** [comment]
Uff, should be ok now :)

Somebody could add a note on documentation about that way of building, or will it remain an "undocumented secret"? :)

**Comment by chipitsine** [comment]
"root added commit..."

**Comment by chipitsine** [comment]
As for documentation, feel free to add proper documentation

**Comment by chipitsine** [comment]
can you please change "From: root <root@pyremc.example.com>" to your github account ?

**Comment by chipitsine** [comment]
@davidebeatrici 
@thepyper 

can you have a look, please ?

https://gitlab.com/chipitsine/alpine-musl
here's CMakeList.txt which (in a way that I've no idea about) ... detects musl

here are builds:

(centos)  https://gitlab.com/chipitsine/alpine-musl/-/jobs/87850559
(alpine)   https://gitlab.com/chipitsine/alpine-musl/-/jobs/87850558


shall we use something like that ?

**Comment by chipitsine** [comment]
musl is also used in LEDE builds, @Andy2244 how do you deal with that ?

**Comment by davidebeatrici** [comment]
> here's CMakeList.txt which (in a way that I've no idea about) ... detects musl

It checks whether `SIGEV_THREAD_ID` is present in `signal.h` or `time.h`, I don't think it's a good way.

**Comment by chipitsine** [comment]
I've found the following http://www.openwall.com/lists/musl/2013/06/26/5

```
One caveat which should not affect your usage is that the following
charsets are only supported as the "from" charset, not the "to"
charset:

eucjp
shiftjis
sjis
gb18030
gbk
gb2312
```

it might be the reason why musl fails in runtime.
however, I successfully converted to "eucjp" using musl. 


detecting ```SIGEV_THREAD_ID``` seems to be the only way.
or not ?

**Comment by Andy2244** [comment]
@chipitsine I just hack it for openwrt:
`$(SED) 's/"eucJP"/"utf-8"/gI' $(PKG_BUILD_DIR)/src/Mayaqua/Internat.c`

**Comment by chipitsine** [comment]
knock-knock, anybody is still here ?

**Pull request merged**
