### PR TITLE
Add parameter "ListenIP" to server configuration (vpn_server.config)

### PR DESCRIPTION
**Pull request by macvk**
VPN server listens on specified IP (0.0.0.0 by default)

### CODE REVIEW

**Comment by dnobori** [comment]
Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

**Comment by silvertriclops** [comment]
Doesn't seem like @macvk is active anymore. Could you guys just add it as option 2 and he can have it changed to option 1 if he wants? I'm eagerly waiting for this too.

**Comment by ayaz** [comment]
Yes. Please. Can we please go with option 2 for now?

**Comment by macvk** [comment]
yes. please go with option 1.

**Comment by tenten8401** [comment]
This should really be added, would be great for multi-ip setups. :+1:

**Comment by aenertia** [comment]
I feel a better way of implementing this as ACL rulesets.

Binding individual IP is specifically excluded for on spec IPv6 socket
listeners for a start.

This needs to be more of a ACL rule than a socket binding operation;
implemented in this fashion it provides additional functionality as well.

If you really need to bind to single interface you can already do so by
running the vpnserver inside a network namespace.

**Comment by qbeukes** [comment]
I tested this change and I am now able to configure the binding IP address using the ServerConfiguration->ListenIP property

**Comment by moatazelmasry2** [comment]
2 years later, but nevertheless this great PR has finally made it into the code :)

**Comment by nikrox2** [comment]
Is this in the binaries or only if complied from the repo?

**Comment by qbeukes** [comment]
Is anyone using this feature successfully in SoftEther 5.1? I had used this previously by manually applying this git change, but after compiling 5.1 from source the same config no longer seems to bind correctly.

I have this setting in vpn_server.config (attached)
declare root
{
  declare ServerConfiguration
  {
     string ListenIP 45.x.x.x
  }
}

[vpn_server.txt](https://github.com/SoftEtherVPN/SoftEtherVPN/files/1838470/vpn_server.txt)

**Comment by fededim** [comment]
I tried this feature on latest build 4.34 build 9745 yet the ListenIP parameter is always deleted whenever I start the softether service...any idea why ? I added to vpn_server.config inside ServerConfiguration section: string ListenIP 172.16.1.101.

**Comment by davidebeatrici** [comment]
The option was not backported to the stable version.

**Comment by fededim** [comment]
Ok thanks, for those interested in the latest nightly version for Windows you can get it from [Azure Devops](https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build?definitionId=6)

**Pull request merged**
