### PR TITLE
vpncmd: Added information about "Disable UDP Acceleration" setting into output of AccountGet command.

### PR DESCRIPTION
**Pull request by mogikanin**
Changes proposed in this pull request:

Added information about "Disable UDP Acceleration" setting into output of AccountGet command.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
The string should also be added to the other languages' string table, even if it's not translated.

**Comment by mogikanin** [comment]
Ok, I'll add. But why app doesn't use default translation (en) if string is missing in current language?

**Comment by davidebeatrici** [comment]
Because only the current language's string table is loaded.

**Comment by mogikanin** [comment]
The string added. Please review and merge.

My question means not why it works in that silly way now, but why you don't change it to work in more logical way. E.g. you could on table loading merge it with en table. In this case all missing translations will be used from en table.

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Pull request merged**
