### PR TITLE
Add support for SOCKS5 proxy protocol

### PR DESCRIPTION
**Pull request by davidebeatrici**
Requested in #746.

VPN Command Line Management Utility:
```
# VPN Client
AccountProxySocks5	Set Connection Method of VPN Connection Setting to be via a SOCKS5 Proxy Server

# VPN Server
CascadeProxySocks5	Set Connection Method of Cascade Connection to be via a SOCKS5 Proxy Server
```

VPN Client Manager:
vpn_client_manager_socks5

VPN Server Manager:
vpn_server_manager_socks5
vpn_server_manager_cascade_socks5

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by chipitsine** [comment]
can we change `Proxy Type` with dropdown box ?

**Comment by davidebeatrici** [comment]
Good idea, but I would do it in another pull request.

**Comment by chipitsine** [comment]
no problem

**Comment by chipitsine** [comment]
radio button is good to two option choice. we can check all the interface, how many choices do we have

**Comment by chinamore** [comment]
After reading your code, I realized that sockes5 is a very complicated implementation method. I think you must spend a lot of time to deal with this function. Thank you for your efforts in the function of sockes5. This function will benefit many people. :
1, when the customer through the sockes5 link can be separated from the routing table, DNS control
2. You can truncate some of the URLs in the first phase of SOCKES5.
3, there are other benefits of SOCKES5: For example, China's lines are divided into individuals, enterprises, dynamic enterprises, static enterprise lines, the above firewalls are different, personal firewalls are the most stringent, static enterprise firewalls are the most lenient, when personal firewalls are discarded When using the server IP, we can use SOCKES5 from the static enterprise line.

**Comment by davidebeatrici** [comment]
Thank you very much for your great feedback!

Do you confirm that the SOCKS5 implementation works for you?

**Comment by chinamore** [comment]
Can I generate a client binary for testing?

**Comment by chinamore** [comment]
indows client binary, I downloaded your 2018-10-30 binary file and finished without sockes5

**Comment by davidebeatrici** [comment]
From AppVeyor: https://ci.appveyor.com/api/buildjobs/airj8d3jfh4bca23/artifacts/output%2Fpkg%2Fv5.01-9661-unstable-2018.10.30%2Fsoftether_open-vpnclient-v5.01-9661-unstable-2018.10.30-windows-x86_x64-intel.exe

**Comment by chinamore** [comment]
The local test link is successful, and going back to test the game UDP will delay at night.

**Pull request merged**
