### PR TITLE
Mayaqua/TcpIp.c: Fix building DHCP static routes in new format

### PR DESCRIPTION
**Pull request by domosekai**
Fix wire format of DHCP Classless Route Option after the refactor of IP.
Address #1399

---

﻿Changes proposed in this pull request:
 - Fix wire format of DHCP Classless Route Option

### CODE REVIEW

**Comment by domosekai** [comment]
@ricksuzade-maker Can you try this fix?

**Comment by paulmenzel** [comment]
Maybe add a Fixes: tag to the commit message.

> Fixes: short commit SHA (commit message summary)

**Comment by domosekai** [comment]
> Maybe add a Fixes: tag to the commit message.
> 
> > Fixes: short commit SHA (commit message summary)

Added. Not exactly sure if this is the way you want.

**Comment by ricksuzade-maker** [comment]
Great JOB!  Works fine until now. Thanks very much!

**Comment by domosekai** [comment]
Thank you for your confirmation.

**Comment by chipitsine** [comment]
Are we ready to merge?

**Comment by domosekai** [comment]
Go ahead.

**Comment by paulmenzel** [comment]
> > Maybe add a Fixes: tag to the commit message.
> > > Fixes: short commit SHA (commit message summary)
> 
> Added. Not exactly sure if this is the way you want.

Perfect. Thank you.

**Pull request merged**
