### PR TITLE
CMake: build all targets in the same directory, so that "hamcore.se2" doesn't have to be copied for each of them

### PR DESCRIPTION
**Pull request by davidebeatrici**
This results in a faster build and less space required.

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by chipitsine** [comment]
I guess launchpad might be affected, @paskal ?

**Comment by chipitsine** [comment]
OpenWRT builds, @andy2244 ?

**Comment by Andy2244** [comment]
@chipitsine What are you asking exactly, if this PR works for my openWRT version? I will have to adapt the makefile, but don't see why it wont, only some output dirs changed?

**Comment by chipitsine** [comment]
@Andy2244 , yes, I meant that. thanks.

**Comment by davidebeatrici** [comment]
@chipitsine The binary is present, see: https://travis-ci.org/SoftEtherVPN/SoftEtherVPN/jobs/442953906#L1309

**Comment by chipitsine** [comment]
can you please reproduce ubuntu 18.04 fresh build including "make package" and investigate resulting deb ?

**Comment by davidebeatrici** [comment]
https://gitlab.com/davidebeatrici/SoftEtherVPN/-/jobs/109588303

**Comment by davidebeatrici** [comment]
https://gitlab.com/davidebeatrici/SoftEtherVPN/-/jobs/109596818

Package: https://gitlab.com/davidebeatrici/SoftEtherVPN/-/jobs/109596818/artifacts/file/build/softether-vpnserver_5.1.9660-1_amd64.deb

**Comment by chipitsine** [comment]
unfortunately, I deleted vm.
give me 30 min

**Comment by davidebeatrici** [comment]
No problem.

**Comment by paskal** [comment]
Should we maybe upload generated deb files from GitLab CI/CD instead of building them in Launchpad? That way new versions will be uploaded as soon as they are ready and we won't have appendix of `debian` folder in separate repo.

**Comment by chipitsine** [comment]
@paskal , there are few thoughts

1) launchpad is running native armh, arm64 build agents. it is good
2) currently we do not support cross builds (but we wish)
3) current deb files include startup scripts only for systemd (if target system supports systemd)
4) we do not know how to upload to launchpad (it would be really nice if you can help here)

**Comment by paskal** [comment]
3. we can include init files as a fallback for 12.04 and other systems without systemd.
4. The upload is [pretty easy](https://help.launchpad.net/Packaging/PPA/Uploading#Using_packages_from_other_distributions)
But because of 2) it's preferable to start doing this after cross builds will be possible, otherwise we can't switch to self builds.

**Comment by chipitsine** [comment]
@davidebeatrici 

```
root@ubuntu-18:~/softethervpn# dpkg -i /home/ilia/softethervpn/build/softether-vpnserver_5.1.9660_amd64.deb
Selecting previously unselected package softether-vpnserver.
(Reading database ... 67327 files and directories currently installed.)
Preparing to unpack .../softether-vpnserver_5.1.9660_amd64.deb ...
Unpacking softether-vpnserver (5.1.9660) ...
Setting up softether-vpnserver (5.1.9660) ...
root@ubuntu-18:~/softethervpn# 

root@ubuntu-18:~/softethervpn# cat /lib/systemd/system/softether-vpnserver.service | grep ExecStart
ExecStart=/usr/local/libexec/softether/vpnserver/vpnserver start
root@ubuntu-18:~/softethervpn# 


root@ubuntu-18:~/softethervpn# ls -l /usr/local/libexec/softether/vpnserver/vpnserver 
ls: cannot access '/usr/local/libexec/softether/vpnserver/vpnserver': No such file or directory
root@ubuntu-18:~/softethervpn# ls -l /usr/libexec/softether/vpnserver/vpnserver 
-rwxr-xr-x 1 root root 2154528 Oct 18 09:54 /usr/libexec/softether/vpnserver/vpnserver
root@ubuntu-18:~/softethervpn# 

```

**Pull request merged**
