### PR TITLE
Russian translate

### PR DESCRIPTION
**Pull request by djony**
Changes proposed in this pull request:
 - Finally almost full Russian translate, exept cli commands. VPN client, server, logs and tools fully translated.  
 - 
 -

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Wow, thank you very much for your contribution!

**Comment by chipitsine** [comment]
@djony sorry for the delay. I'm ready to merge, however there are conflicts :(
can you please address it one more time and I'll merge right after ?

**Comment by djony** [comment]
I will check changes and send new request

**Comment by davidebeatrici** [comment]
No problem, I unmerged this pull request because all 184 commits ended up in `master`.

**Comment by chipitsine** [comment]
Yeah, let the disco begin ))

**Comment by chipitsine** [comment]
Sorry for that

**Pull request merged**
