### PR TITLE
Set unbuffered mode for *nix systems stdout, allowing interactive use…

### PR DESCRIPTION
**Pull request by MatAtBread**
… within spawned processes. Fixes issue #898

### CODE REVIEW

**Comment by chipitsine** [comment]
is it POSIX (will it work for osx as well) ?

**Comment by MatAtBread** [comment]
Yes, it should work on OSX (see https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/setbuf.3.html). 

I tested on Ubuntu 18.04 and it worked as expected. It doesn't, however work on WSL (Windows Subsystem for Linux) Ubuntu, but that's know to have some unusual behaviours. If I had to guess, I'd say it's simply being ignored, as the behaviour was identical to the version without the `setbuf` call.

**Comment by chipitsine** [comment]
I'm not sure how it should work on WSL

**Comment by chipitsine** [comment]
stay tuned, I will make a release of SE VPN developer edition

**Pull request merged**
