### PR TITLE
Add SE_ Prefix to header guards

### LINKED ISSUE #3: Make include guards unique
I find that include guards like "[ACCOUNT_H](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/749497dde0a1dd08c434a73b9d4e93dc3e3326d9/src/Cedar/Account.h#L84)" and "[CM_H](https://github.com/SoftEtherVPN/SoftEtherVPN/blob/749497dde0a1dd08c434a73b9d4e93dc3e3326d9/src/Cedar/CM.h#L84)" are too short for the safe reuse of your header files.

### PR DESCRIPTION
**Pull request by moatazelmasry2**
Changes proposed in this pull request:
 -  This PR resolves #3 : "Make header guards unique". This is indeed an issue because many header files have simple guards like ACCOUNT_H or ADMIN_H which might exist in other library and thus causing a naming clash.
- By adding SE_ Prefix this issue should be resolved
  

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- Option 1

### CODE REVIEW

**Comment by macvk** [comment]
why you do it? can you please provide an example of conflict?

**Comment by moatazelmasry2** [comment]
Let us say you are using SoftEther source code in your own project which
also include other libraries. It is possible that other libraries are also
using ADMIN_H or similar which will cause an error since the header files
of SoftEther can not be included.

**Comment by macvk** [comment]
Sorry, this problem seems far-fetched. it's only my own opinion. want to use SE in third-party projects? you need to create something like library from SE...

**Comment by moatazelmasry2** [comment]
What do @SoftEtherVPN/softether-development-board-members  think? Otherwise we can just close issue #3 without resolving

**Comment by GildedHonour** [comment]
I agree with the change but I'd make the prefix longer, for instance - SFT_ETH or SOF_ETH

**Comment by zulzardi** [comment]
I'm agree with both. But if u want to add the the prefix I think better go to @GildedHonour way. The best option create the library and it will solved any conflict.

**Comment by macvk** [comment]
> What do @SoftEtherVPN/softether-development-board-members think? Otherwise we can just close issue #3 without resolving

this is not issue at all

**Comment by moatazelmasry2** [comment]
Please thumb up or down this pull request

**Comment by zulzardi** [comment]
👍

**Pull request closed without merging**
