### PR TITLE
Autotools support and FHS compliance

### PR DESCRIPTION
**Pull request by dajhorn**
(Rebased on the SoftEther 4.10.9505 beta release.)

This branch enhances SoftEther with:
- Autoconf, automake, and libtool support.
- Compliance with the Filesystem Hierarchy Standard.

The motivation for this work is:
- Debian Policy Conformance.
- Dynamic linking for binary size and memory optimization.
- Better portability, especially for embedded systems that are not based on glibc.  (eg: uclibc)

Binary packages for Ubuntu are published here:
- https://launchpad.net/~dajhorn/+archive/softether

With these changes, the payload size for all four utilities is 1.7 megabytes and the maximum RSS is less than 20 megabytes.

### CODE REVIEW

**Comment by moatazelmasry2** [comment]
I personally prefer CMake over Autotools,, as it is easier to understand and manage. What do the other contributors  think????

**Comment by davidebeatrici** [comment]
CMake pull request: #518

**Comment by moatazelmasry2** [comment]
Hi @dajhorn. We merged PR #518 which makes use of cmake. Would you like to isolate the FHS changes into its own PR?

**Comment by moatazelmasry2** [comment]
Closing this for now. Since cmake is in use now. Sorry

**Pull request closed without merging**
