### PR TITLE
Mayaqua: use included zlib headers only on Windows

### PR DESCRIPTION
**Pull request by davidebeatrici**
`zlib` doesn't have a dedicated directory, because it has a single header.

`zconf.h` is additional.

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by chipitsine** [comment]
does this mean some implification like "linux might use bundled zlib.h as well, so we relocate zlib.h into deeper folder, to make sure linux will load system zlib.h" ?

**Comment by davidebeatrici** [comment]
Exactly.

**Comment by chipitsine** [comment]
I recall pretty complicated story of bundling "zlib" into base in openvpn


patch is nice (while commit message might reflect changes in more clear way)

as for future, I'd say we need to do something with that.
for example, use zlib from nuget (on windows). it is hard to maintain bundled zlib

**Comment by davidebeatrici** [comment]
I updated the commit message.

**Comment by chipitsine** [comment]
I'll have a look bit later.

what do you think, shall we add an issue of moving binary dependencies (openssl, zlib) to nuget ?

**Comment by davidebeatrici** [comment]
Yes.

**Pull request merged**
