### PR TITLE
Unix.c: don't use hardcoded path to call "ethtool"

### LINKED ISSUE #300: Unix: Bridge doesn't reliable disable offloading because of hardcoded ethtool path
We noticed a performance problem on our vpn server which was caused by active _generic receive offloading_ (gro)  on the bridged network card.

SoftEtherVPN attempts to disabled all offloading, but does this by using /sbin/ethtool for the operation.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/src/Mayaqua/Unix.c#L367

In our environment ethtool is not available in /sbin but in /usr/sbin, so the attempt failed. In my opinion, SoftEtherVPN shouldn't assumed fixed paths for this and any other external command, but rely on the environment instead.

### PR DESCRIPTION
**Pull request by davidebeatrici**
Fixes #300.

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by chipitsine** [comment]
what if ethtool is not installed ?

**Comment by davidebeatrici** [comment]
The call fails.

**Comment by chipitsine** [comment]
yeah, it fails regardless to your patch.

but it is nice time to review such things if we touch that code anyway

**Comment by davidebeatrici** [comment]
I agree.

**Comment by chipitsine** [comment]
what also came to mind, "/sbin" is usually available in root $PATH variable, but not in regular user.

**Comment by davidebeatrici** [comment]
Yes, because `ethtool` requires root permissions.

**Comment by chipitsine** [comment]
I understand. "/sbin" is part of interactive shell $PATH, is it true for SE VPN as well ? I'll check tomorrow

**Pull request merged**
