### PR TITLE
CI: enable GHA macos builds

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
@barracuda156 , please review

**Comment by barracuda156** [comment]
@chipitsine I am afraid I cannot be useful with CI setups.

@catap Could you take a quick look at this?

**Comment by barracuda156** [comment]
@chipitsine On our buildbots everything is good: https://ports.macports.org/port/softether5/details
(Build failure on 10.7 and 10.10 look superficial and unrelated to `softether` itself; all other versions are good, including PowerPC build – the latter verified locally, no buildbot for it atm.)

**Comment by chipitsine** [comment]
@barracuda156 , what is "macports" ?

if that is kind of package manager, can you add a link to it to our doc ?
how regular ar those builds ? can we add badge ?

**Comment by barracuda156** [comment]
@chipitsine [Macports](https://ports.macports.org) is one of the two arguably most widely used package managers on macOS. (It _might_ also work on Linux and FreeBSD, but that is seldom tested.)

Buildbots will rebuild a port every time it is updated. A user may choose to install a pre-built package then or build from source.

Yes, I can add a reference in install-for-macOS section, if it is there.

**Comment by chipitsine** [comment]
great, we'll appreciate that

**Pull request merged**
