### PR TITLE
Clean up Solaris device name parsing code to eliminate Coverity errors

### PR DESCRIPTION
**Pull request by hww3**
Changes proposed in this pull request:
 - proposed fix for CID 305724 and CID 305725 by removing unneeded loop structures.

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- Option 1

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Wait before merging, I'm doing some changes.

**Comment by chipitsine** [comment]
We are looking for Solaris to be attached as gitlab-ci build agent. If you
wish to volunteer it would be nice

**Comment by davidebeatrici** [comment]
@hww3 I wanted to set your GitHub email address in the commit so that it counts as contribution, but it's not public.

You can set it with:
`git commit --amend --reset-author --author="Bill Welliver <email>"`

**Comment by davidebeatrici** [comment]
Sorry, I didn't specify that you had to do `git pull -f` in order to update your local branch.

I removed the last commit and set your email in the correct one.

**Comment by hww3** [comment]
> We are looking for Solaris to be attached as gitlab-ci build agent. If you wish to volunteer it would be nice

I suppose I could volunteer to do that.  Assume that means a box running the gitlab ci runner and such... has anyone else already done this for another platform that might have tips?

**Comment by chipitsine** [comment]
please write something in https://github.com/SoftEtherVPN/SoftEtherVPN/issues/668

yes, that exactly means attaching gitlab-ci runner to https://gitlab.com/SoftEther/SoftEtherVPN

for the very first time you can attach runner to your own repo. when it is ready, feel free to make a PR on .gitlab-ci.yml (and ask someone to attach your runner)

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Pull request merged**
