### PR TITLE
travis-ci: split openssl into 1.0.2, 1.1.0 matrix

### PR DESCRIPTION
**Pull request by chipitsine**
Changes proposed in this pull request:
 - introducing openssl-1.1.0 in travis-ci builds

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- one

### CODE REVIEW

**Comment by chipitsine** [comment]
@moatazelmasry2 , @davidebeatrici - I'd like to get review from you

**Comment by chipitsine** [comment]
ok, that makes sense

**Comment by davidebeatrici** [comment]
There's a problem though.

The 1.1.0f builds have the system's OpenSSL libraries as dependencies, according to `ldd`:

```
$ ldd bin/vpnserver/vpnserver
	linux-vdso.so.1 =>  (0x00007ffd1cefe000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1f6f4e5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1f6f2c7000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f1f6f068000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f1f6ec8c000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f1f6ea46000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007f1f6e823000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1f6e60a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1f6e241000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1f6f6ed000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1f6e03d000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f1f6de14000)
```

**Comment by chipitsine** [comment]
@davidebeatrici , thank you for your attention.
I sure I eye witnessed (on my laptop) proper ldd

we definetly need better detection of "is softethervpn linked to the proper openssl lib" and we need better build system (something like autoconf or cmake)

**Comment by davidebeatrici** [comment]
@chipitsine I agree.

**Comment by moatazelmasry2** [comment]
Nothing to add here. Looks great and I was hoping for a long time, that someone will finally create a simple matrix for travis-ci. This will definitely make our life easier. 

I also totally agree that we need a a functioning build system, one that is capable of cross compiling obviousely build windows binaries among others. I'm considering cmake with wingw or so. 

Anyways I'm accepting your merge. Many thanks for your excellent work.

**Comment by moatazelmasry2** [comment]
One question though, how did you do multiple commits and they appear here as one commit?

**Comment by davidebeatrici** [comment]
It isn't, but you have to push forcibly: `git push --force` or `git push -f`.

It's kind of dangerous because you have to be careful if someone else is working on the same branch, otherwise you risk overwriting his commits if your local branch is not up-to-date.

This can be avoided by using `git push --force-with-lease`, which checks that your local branch is up-to-date before pushing.

There's a great article explaining in detail: https://evilmartians.com/chronicles/git-push---force-and-how-to-deal-with-it

**Comment by moatazelmasry2** [comment]
@davidebeatrici thanks

**Comment by moatazelmasry2** [comment]
It is indeed a bit dangerous. I'll just stick to squashing and rebasing commits when accepting a PR :)

**Comment by davidebeatrici** [comment]
> @davidebeatrici thanks

@moatazelmasry2 You're welcome.

> It is indeed a bit dangerous. I'll just stick to squashing and rebasing commits when accepting a PR :)

I think that's the best thing to do, as the previous pull requests have been merged this way.

Starting to squash and rebase the commits directly in the branch and then merging it via a merge commit would probably cause confusion in the master branch's commits list.

**Comment by chipitsine** [comment]
@moatazelmasry2 , do you mean Settings --> Merge button --> ... ? Or do you manually squash those commits during merge ?

well, I also hoped that I'll do simple travis-ci and someone will see it and develop into real matrix. seems, I need to do it myself

**Pull request merged**
