### PR TITLE
CI: move stb check from travis-ci to GHA

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
@djony , can you please review findings

https://github.com/SoftEtherVPN/SoftEtherVPN/actions/runs/5980139266/job/16225650176?pr=1894#step:3:289

**Comment by djony** [comment]
Hi chipitsine
I changed line endings in file from LF to CR LF like in other language files and found translation errors in lines, that don't gave you make merging
I created pull request #1895 for fix that. Hope it's help

**Comment by djony** [comment]
I saw one error in line CM_IMPORT_MESSAGE. Perhaps this is due that I have swapped in line the variables "S" and "s", that in Russian the translation sounded better.

**Comment by chipitsine** [comment]
I;ve changed "%S" and "%s" in https://github.com/SoftEtherVPN/SoftEtherVPN/pull/1894/commits/68e704097d96b22f3920a3c69881c9d0907735b5

currently, order of substitutes cannot be changed

**Pull request merged**
