### PR TITLE
Japanese: translate LH_AUTH_NG again

### PR DESCRIPTION
**Pull request by metalefty**
It regressed to English in #1122.

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Could you squash the commits, please?

**Comment by metalefty** [comment]
Squashed.

**Comment by davidebeatrici** [comment]
Thanks.

**Comment by benrubson** [comment]
@metalefty @davidebeatrici keep in mind that goal of these messages is to be caught by Fail2Ban.
If you translate them, Fail2Ban jail won't work anymore.
I then think they should be kept in english.

**Comment by metalefty** [comment]
I've been worked on `blacklistd(8)`, a similar product of fail2ban, of BSD.  I would say fail2ban relies on scraping human-oriented logs too much. 

Not translating logs only for fail2ban is a bad idea and spoils the user experience because the log is also for humans. I think users who want to use fail2ban should set the language settings to English otherwise we should also introduce machine-oriented logs for fail2ban like:

```C
LH_AUTH_NG_F2B   [fail2ban] AUTH_NG: CID="%S", USER="%S", CLIENT_IP="%S"
```

Then we can be friendly both to humans and fail2ban.

**Comment by benrubson** [comment]
> I think users who want to use fail2ban should set the language settings to English

I then think that's the proper solution if we want all messages to be translated (so this PR to be merged).
A specific fail2ban message, is, well, too specific IMO, as, as you said, there are other blacklisting solutions.
Let's go like this then if all messages must be translated 👍

**Comment by chipitsine** [comment]
how we go further ? should we merge it ?

**Comment by metalefty** [comment]
As far as I observe, many Japanese users want Japanese messages as much as possible if the language is set to Japanese. I would like to go this way. Translate as much as possible and add some machine-friendly log messages for machine-reading purposes.

**Pull request merged**
