### PR TITLE
Cedar/CM.c: Fix wrong shortcut key assignment in the menu

### LINKED ISSUE #1702: Windows Client: Ctrl+O should open options but opens traffic tool
## Prerequisites

* [x] Can you reproduce?
* [x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** I'm using this build artifact.

* https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build/results?buildId=932&view=results

**Component:** Client
**Operating system:** Windows
**Architecture:** 64 bit

### Description

**Expected behavior:**
Options should open when pressing Ctrl+O

**Actual behavior:**
Traffic tool will open.

### Steps to reproduce

1. Install SoftEtherVPN client 
2. Press Ctrl+O on keyboard
3. Options should open but traffic tool will open

image

### PR DESCRIPTION
**Pull request by metalefty**
Fixes #1702.

Thanks, @domosekai!

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Typo in commit message: `asignment` -> `assignment`

I would also specify the shortcut key that is fixed and where.

**Comment by metalefty** [comment]
Let me some time to fix typo.

**Comment by domosekai** [comment]
This only fixes the easy mode. Normal mode is in `CmOnKey`, where the code is the same.

**Comment by metalefty** [comment]
Indeed,  updated.

**Comment by domosekai** [comment]
Merged. Thank you.

**Pull request merged**
