### PR TITLE
Foreground logging

### PR DESCRIPTION
**Pull request by joshperry**
This is the first in couple of patches to make softether compatible with running inside an immutable, stateless, container. We currently run softether on top of kubernetes as a docker container and have run into a number of design decisions that make it very difficult.

In a containerized infrastructure, it is almost a rule that processes do not daemonize and direct their logging output to stdout. This is because the container process runs as PID 0 inside the container, and the process's stdout is collected by the infrastructure logging facility.

Changes proposed in this pull request:
 - Create a `--foreground` command line option so that the service does not daemonize
 - In foreground mode the service will log only to stdout and not to log files

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- We are fine with our code being used in proprietary products under the terms of a BSD/MIT-like OSS license.

PRELIMINARY DECLARATION FOR FUTURE SWITCH TO A NON-GPL LICENSE

I hereby agree in advance that my work will be licensed automatically under the Apache License or a similar BSD/MIT-like open-source license in case the SoftEther VPN Project adopts such a license in future.

### CODE REVIEW

**Comment by chipitsine** [comment]
are you going to resolve https://github.com/SoftEtherVPN/SoftEtherVPN/issues/93 ?

**Comment by chipitsine** [comment]
windows build is broken

https://ci.appveyor.com/project/SoftEtherVPN/softethervpn/build/build-243-22f8d26#L234

can you wrap code with ```#ifdef	OS_UNIX``` ?

**Comment by joshperry** [comment]
I did not see #93, but yes it should resolve that. I'll take care of deffing out windows.

**Comment by joshperry** [comment]
@chipitsine I've fixed the Windows build and updated the description with our patch policy acceptance..

**Comment by chipitsine** [comment]
great, we'll review in few days

**Pull request merged**
