### PR TITLE
Remove SSLv3 support

### PR DESCRIPTION
**Pull request by davidebeatrici**
SSLv3 is currently disabled by default:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/412a5aea71b0ace24fc76827dfc203655877a021/src/Cedar/Server.c#L2553-L2554

This pull request removes that option and the one in the client manager which disables TLS.

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by moatazelmasry2** [comment]
Please clear this PR with Daiyuu. Since it violates the developers Guide:
Do not change behavior.

From my side : great PR. Go for it 😁

**Comment by davidebeatrici** [comment]
SSLv3 was already disabled by default:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/412a5aea71b0ace24fc76827dfc203655877a021/src/Cedar/Server.c#L2553-L2554

**Comment by davidebeatrici** [comment]
This pull request also fixes #408.

**Comment by BlackHoleFox** [comment]
Out of curiosity, if it disables TLS entirely, what does it use instead of it?

**Comment by davidebeatrici** [comment]
SSLv3, see #624.

**Pull request merged**
