### PR TITLE
Implement support for WireGuard

### PR DESCRIPTION
**Pull request by davidebeatrici**
Reviews are welcome!

### CODE REVIEW

**Comment by davidebeatrici** [comment]
Right now `ProtoOptionsGet` doesn't require the caller to be a server administrator, but the behavior should probably be changed now that the WireGuard private and preshared keys are there.

**Comment by metalefty** [comment]
I can help you with Japanese translation.

**Comment by davidebeatrici** [comment]
Awesome, thank you very much!

@dnobori usually translates to Japanese for me, but he's very busy right now.

**Comment by metalefty** [comment]
I've just started to translate existing untranslated messages in the separate PR #1201.

**Review by metalefty — COMMENTED** [review]
It might be better to focus on reviewing the logic of new code in this PR. Translations can be done later.

So what about adding some markers around untranslated messages? Then, I and other contributors can easily find untranslated messages later.

```
# TODO:  TO BE TRANSLATED
```

**Comment by davidebeatrici** [comment]
I agree, I'll do that in a separate pull request for all `.stb` files.

**Comment by andrewfer000** [comment]
So umm is this going to get merged soon? This feature is super cool and it looks like you put a lot of work into it. I would love to see it in one of the next releases.

**Comment by davidebeatrici** [comment]
I'm actually waiting for feedbacks.

**Comment by davidebeatrici** [comment]
BLAKE2's CMake project wrongly detects the available instruction sets:

```
-- Build date: 12/10/2020
-- Build time: 19:11:24
-- Finding best ISA extension...
-- Selected AVX2
-- Configuring for SSE or newer
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/SoftEtherVPN/build
```

```gdb
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f14b3fd49b0 in blake2s_init_param () from /home/user/SoftEtherVPN/build/libcedar.so
[Current thread is 1 (Thread 0x7f14b26ec440 (LWP 12380))]
(gdb) bt
#0  0x00007f14b3fd49b0 in blake2s_init_param () from /home/user/SoftEtherVPN/build/libcedar.so
#1  0x00007f14b3fd4a5c in blake2s_init () from /home/user/SoftEtherVPN/build/libcedar.so
#2  0x00007f14b3fd4f6c in blake2s () from /home/user/SoftEtherVPN/build/libcedar.so
#3  0x00007f14b3f925aa in WgsInit () from /home/user/SoftEtherVPN/build/libcedar.so
#4  0x00007f14b3f72582 in ProtoSessionNew () from /home/user/SoftEtherVPN/build/libcedar.so
#5  0x00007f14b3f72916 in ProtoHandleDatagrams () from /home/user/SoftEtherVPN/build/libcedar.so
#6  0x00007f14b3e309d7 in UdpListenerThread () from /home/user/SoftEtherVPN/build/libmayaqua.so
#7  0x00007f14b3e16115 in ThreadPoolProc () from /home/user/SoftEtherVPN/build/libmayaqua.so
#8  0x00007f14b3e4e93c in UnixDefaultThreadProc () from /home/user/SoftEtherVPN/build/libmayaqua.so
#9  0x00007f14b3335fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007f14b3ca74cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 6
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1
cpu MHz         : 2397.384
cache size      : 16384 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 4794.76
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

```

```

**Comment by andrewfer000** [comment]
I'd like to test this. I cloned the `davidebeatrici:proto-wireguard` and compiled it but I got no Wg commands. How do I go about obtaining and compiling the code so I can test out WireGuard?

**Comment by andrewfer000** [comment]
So I am trying to get the public key for Wireguard but I do not know where to find it. Both WkgEnum and ProtoOptionsGet/ProtoOptionsSet are unsupported. How do I get WireGuard set up?

**Comment by davidebeatrici** [comment]
You have to derive it from the private one (obtainable through `ProtoOptionsGet`).

See https://www.wireguard.com/quickstart.

**Comment by andrewfer000** [comment]
@davidebeatrici 
I saw that in the original Github issue. The problem is with ProtoOptionsGet. This command is driving me crazy!

image

**Comment by davidebeatrici** [comment]
The name of the protocol is `WireGuard`, but the comparison is case insensitive:
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/5f12684b42f747c2d15f3b89a03133c15dd902ea/src/Cedar/Proto.c#L60-L73

Are you sure the server you're running is compiled from my branch?

**Comment by andrewfer000** [comment]
Okay so I just had to restart the vpnserver service and it works now. Thanks!

**Comment by davidebeatrici** [comment]
I just rebased against `master`.

If you pull from my branch and build the server again you should not see the issue anymore, assuming it doesn't show up in `master`.

**Comment by andrewfer000** [comment]
I think it does show up in master and I believe I mentioned that in issue #1241

**Comment by davidebeatrici** [comment]
Sorry, you're right.

**Comment by davidebeatrici** [comment]
I fixed the instruction set detection issue and restricted `ProtoOptionsGet` to server administrators, in order to protect the WireGuard private key.

@andrewfer000 Have you encountered any issues with the WireGuard implementation so far?

**Comment by andrewfer000** [comment]
@davidebeatrici not at all. WireGuard has been working well. The only issue is I have encountered or the ones on my LG Android but that's it. Overall very stable.

**Comment by davidebeatrici** [comment]
Awesome!

My branch is actually already rebased against `master`, feel free to test the latest changes.

As for your LG V30, is there perhaps something related to WireGuard in Android's logcat?

**Comment by Gaulomatic** [comment]
I downloaded the latest Azure artifacts from Azure for Windows and compiled the Linux sources and tried it on Windows and Linux. I am not able to connect to the server with WireGuard, neither on Win nor on Linux.

I am seeing this in the server logs:

image

The Windows client tells me that the handshake failed:

image

I have added the client keys via the command line interface, they are listed properly and WireGuard protocol is enabled (as it is by default). The keys are mapped to users on a virtual hub. Is there something else to configure that I might have missed?

**Comment by davidebeatrici** [comment]
Have you set the server's public key in the client?

**Comment by Gaulomatic** [comment]
The keys were my first line of thinking as well, so I tripple checked all those. Is there any way to let SoftEther be a little bit more verbose so I can get down to the cause?

**Comment by davidebeatrici** [comment]
`./vpntest s`

**Comment by Gaulomatic** [comment]
Thanks, that is good to know. I created completely new keys, server and client, and imported them to SoftEther. Now the client tells me that the response from SoftEther is giving an invalid response:

image

This is the output from `./vpntest s`

image

**Comment by davidebeatrici** [comment]
To be clear: you imported the **public** keys in both client and server, right?

**Comment by Gaulomatic** [comment]
Yes, I exported the config and set the PresharedKey (public) and PrivateKey (private) key which `wg genkey` generated for me. 

image

I did the same with the clients and edited the KeyList accordingly:

image

Lastly I updated the WireGuard client config:

image

I set up a vanilla WireGuard server on a different machine using Ubuntu 18.04 and used the same public and private keys for client and server. This works correctly.

**Comment by davidebeatrici** [comment]
`PresharedKey` must be set on all peers. Please note that:

1. It's an additional key, for extra security.
2. It should be different from the public key.

Here's the correct block:
```ini
[Peer]
PublicKey = RjU8BHHngBKdNSJZIKx2+Xb0MleURvnM5ZxKmGDzpAw=
PresharedKey = RjU8BHHngBKdNSJZIKx2+Xb0MleURvnM5ZxKmGDzpAw=
AllowedIPs = 172.16.0.0/16
Endpoint = 192.168.31.195:5555
```

**Comment by Gaulomatic** [comment]
Thank you, that did it. I have mistaken the preshared with the public.

**Comment by davidebeatrici** [comment]
You're welcome! We definitely need to document the configuration.

**Comment by paulmenzel** [comment]
@Gaulomatic, thank you for reporting this, but please create an issue for this the next time.

**Comment by metalefty** [comment]
The WireGuard support is actually working fine for me. Thanks for your hard work! I'll help you by improving documentation and Japanese translation. 

スクリーンショット_2021-03-22_22-00-20
スクリーンショット_2021-03-22_22-01-31

**Comment by davidebeatrici** [comment]
Awesome, thank you very much!

**Comment by hoang-rio** [comment]
@davidebeatrici Is WireGuard available for Radius user?

**Comment by davidebeatrici** [comment]
Yes, but you have to associate the public key to it.

**Comment by hoang-rio** [comment]
I only add user * with radius authentication to manage all user and password in a radius server so how to associate public key to specific radius user? `*.username` or something else

**Comment by davidebeatrici** [comment]
Just the username actually and destination hub actually. We should eventually implement a way to check the public key against Radius.

**Comment by qupfer** [comment]
Simple question,
the connection is etablished, but "how" I get the traffic from Softether to the bridged network? It looks like in "hangs" in the virtual hub. Only with secure-nat?

**Comment by davidebeatrici** [comment]
How's your setup?

**Comment by qupfer** [comment]
Its a ubuntu 22.04 lxc container (on proxmox) with the default hub bridged to eth0 (Softether build from yesterdays gitlab-src ).
I left the hub-config to its default 192.168.30.1/24, the eth0 net is 192.168.178.0/24. The wg-clint use 192.168.30.2.
I started  a ping from the wg-client to 192.168.30.1 and watched eth0 on server side, but couldn't see anything.

**Comment by davidebeatrici** [comment]
You're not supposed to enable Virtual NAT with a local bridge, you can use Virtual DHCP though.

**Comment by hoang-rio** [comment]
When wiguard configurable via JSON-RPC API?

**Pull request merged**
