### PR TITLE
Add DhParamBits configuration to set Diffie-Hellman parameters

### PR DESCRIPTION
**Pull request by nvsofts**

### CODE REVIEW

**Comment by dnobori** [comment]
Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

**Comment by nvsofts** [comment]
Thank you for considering my pull request.
I choose option 1.

**Comment by moatazelmasry2** [comment]
Hi @nvsofts this is a great patch and I'd love to merge it. Could you please resolve the conflicts so that we can merge it please???

**Comment by pdarcos** [comment]
I too think this is a great patch and much needed.
+1

**Comment by moatazelmasry2** [comment]
Your PR has been merged. I had to rename some stuff since the naming convention is currently messed up. Never the less it is a great PR. Thank you for your hard work. As a token of gratitude your name has been added to authors list. Cheers

**Pull request merged**
