### PR TITLE
Cedar: Make OpenVPN timeout and ping transmission interval configurable

### PR DESCRIPTION
**Pull request by davidebeatrici**
Also, the default timeout value is set to 30000 (milliseconds) instead of 10000.

The change is made because it was reported that some routers failed to connect in time: #495

---

This PR also fixes a bug which caused the server to initialize all boolean options to false.

It was caused by `SiLoadProtoCfg()` not checking whether the item exists in the configuration file.

`CfgGetBool()` always returns false if the item doesn't exist.

### CODE REVIEW

**Comment by dnobori** [comment]
I suppose that this should be editable on the configuration file. The default value should same to the existing constants.


Altering the default behavior by editing the constants in the header file is not a good idea.

**Comment by davidebeatrici** [comment]
Making the intervals editable via the configuration file would be ideal.

However, I think that we should edit the constants anyway, as the current intervals are too low to be suitable for slow connections or devices.

**Comment by davidebeatrici** [comment]
True.

**Comment by moatazelmasry2** [comment]
@davidebeatrici would you then like to amend this PR? or do you want to create a new one?

**Comment by davidebeatrici** [comment]
@moatazelmasry2 I would like to keep this one.

**Comment by davidebeatrici** [comment]
Done.

**Review by chipitsine — APPROVED** [review]

**Pull request merged**
