### PR TITLE
Cedar: retrieve the list of available encryption algorithms from the server

### PR DESCRIPTION
**Pull request by davidebeatrici**
Requested in #360.

---

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

I choose option 1.

### CODE REVIEW

**Comment by solipse** [comment]
@chipitsine 
In OpenBSD command ServerCipherGet don't retrieve the list of available encryption algorithms.
Retrieve only currently used algorithm.

**Comment by chipitsine** [comment]
@solipse , LibreSSL ?

**Comment by solipse** [comment]
@chipitsine , yes LibreSSL

**Comment by chipitsine** [comment]
we definitely miss tests ((

**Comment by solipse** [comment]
This is not very important to me, just take note

**Comment by chipitsine** [comment]
can you please fill an issue on that?

**Comment by solipse** [comment]
https://github.com/SoftEtherVPN/SoftEtherVPN/issues/861

**Pull request merged**
