### PR TITLE
WIP: remove unused functions (identified by cppcheck)

### PR DESCRIPTION
**Pull request by chipitsine**
[src/Cedar/Hub.c:6663]: (style) The function 'CalcTrafficEntryDiff' is never used.
[src/Mayaqua/Cfg.c:539]: (style) The function 'CfgRead' is never used.
[src/Mayaqua/Cfg.c:1429]: (style) The function 'CfgStrToType' is never used.
[src/Mayaqua/Network.c:7782]: (style) The function 'CheckSubnetLength6' is never used.
[src/Mayaqua/Network.c:14614]: (style) The function 'CheckTCPPortThread' is never used.
[src/Cedar/WinUi.c:9257]: (style) The function 'CheckTextLen' is never used.
[src/Cedar/WinUi.c:9238]: (style) The function 'CheckTextSize' is never used.
[src/Mayaqua/Network.c:6827]: (style) The function 'CheckUnicastAddress' is never used.
[src/Mayaqua/Encrypt.c:2748]: (style) The function 'CheckX' is never used.
[src/Cedar/Client.c:10394]: (style) The function 'CiFreeInnerVPNServer' is never used.
[src/Cedar/Client.c:10785]: (style) The function 'CiGetNumActiveSessions' is never used.
[src/Cedar/Client.c:2042]: (style) The function 'CiHasAccountSensitiveInformationFile' is never used.
[src/Cedar/Client.c:10377]: (style) The function 'CiNewInnerVPNServer' is never used.
[src/Mayaqua/Secure.c:842]: (style) The function 'CkDateToUINT64' is never used.
[src/Mayaqua/Memory.c:2605]: (style) The function 'ClearFifo' is never used.
[src/Mayaqua/Memory.c:4267]: (style) The function 'CloneTail' is never used.
[src/Cedar/Command.c:9739]: (style) The function 'CmdEvalIpAndMask46' is never used.
[src/Cedar/Command.c:9826]: (style) The function 'CmdEvalNetworkAndSubnetMask46' is never used.
[src/Cedar/Command.c:22767]: (style) The function 'CmdPrintRow' is never used.
[src/Cedar/Client.c:1128]: (style) The function 'CncGetSessionId' is never used.
[src/Cedar/Client.c:767]: (style) The function 'CncPasswordDlgHaltThread' is never used.
[src/Cedar/Client.c:10589]: (style) The function 'CompareInternetSetting' is never used.
[src/Cedar/Protocol.c:907]: (style) The function 'CompareNodeInfo' is never used.
[src/Cedar/Session.c:1853]: (style) The function 'CompareSession' is never used.
[src/Mayaqua/Network.c:8171]: (style) The function 'CompareTcpTable' is never used.
[src/Mayaqua/Tracking.c:593]: (style) The function 'CompareTrackingObject' is never used.
[src/Mayaqua/FileIO.c:728]: (style) The function 'ConvertSafeFileNameW' is never used.
[src/Mayaqua/Str.c:2024]: (style) The function 'CopyBinToStr' is never used.

Changes proposed in this pull request:
 - remove unused functions

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

- 1

### CODE REVIEW

**Comment by chipitsine** [comment]
@moatazelmasry2 , there are 500+ unused functions. I think, the most comfortable is 20-30 per PR. If you prefer to review 500+ removed functions in a single PR, I can open such PR

**Comment by moatazelmasry2** [comment]
Hi @chipitsine . Just add the other changes directly to this PR.

Thanks and cheers

**Comment by chipitsine** [comment]
I'll remove "WIP" when it is finished

**Comment by chipitsine** [comment]
I will reopen it

**Pull request closed without merging**
