### PR TITLE
cppcheck findings

### PR DESCRIPTION
**Pull request by chipitsine**
issues were identified by running (cppcheck)

```
script
cppcheck --force --enable=all
Ctrl-D
grep '(error' typescript
grep '(warning' typescript
```

and (clang static analyzer)

```
./configure
scan-build make
```

identified issues are mostly related to "derefence var before checking againts NULL"
cppcheck findings are described in their commit messages

### CODE REVIEW

**Comment by chipitsine** [comment]
"option 1" according to http://www.softether.org/5-download/src/9.patch

**Comment by moatazelmasry2** [comment]
Could you please add some dexcription to the PR?? Thank you

**Comment by chipitsine** [comment]
ok, lets start with the following description:

issues were identified by running 

```
script
cppcheck --force --enable=all
Ctrl-D
grep '(error' typescript
grep '(warning' typescript
```

and 

```
./configure
scan-build make
```

identified issues are mostly related to "derefence var before checking againts NULL"

**Comment by moatazelmasry2** [comment]
@chipitsine please adapt the PR description accordingly instead of writing a comment. Thanks

**Comment by moatazelmasry2** [comment]
Your PR has been merged. Thank you for your hard work

**Pull request merged**
