### PR TITLE
upgrade Zdos" OS inside

### PR DESCRIPTION
**Pull request by madkali**
Changes proposed in this pull request:
 - fusion?
 - 
 -

### CODE REVIEW

**Comment by chipitsine** [comment]
what is a meaning of having that file ?

**Comment by madkali** [comment]
hello, my name is roberto, I'm not a computer scientist but a
cyberpunk chef born in 85.
I forked from zcash the zdos, joined it to your software ... I would
like to create an operating system like collapses OS and integrate
these three points a maximum 128 bit gameing platform ... and feasible
or am I just a fool?


Il giorno dom 13 ott 2019 alle ore 17:07 Ilya Shipitsin <
notifications@github.com> ha scritto:

**Comment by madkali** [comment]
si puo unire ?

**Comment by madkali** [comment]
si puo provare l'integrazione vpn e zdos?

**Comment by chipitsine** [comment]
how that file is supposed to be used ?

**Comment by madkali** [comment]
man,😓 i do no...

Il dom 13 ott 2019, 5:45 PM Ilya Shipitsin <notifications@github.com> ha
scritto:

**Comment by madkali** [comment]
si puo creare un mining per il mio Zdos tramite il vpn gateway

**Pull request closed without merging**
