### PR TITLE
Add debug print for dbgview.exe( www.sysinternal.com ) or other debug…

### PR DESCRIPTION
**Pull request by tidatida**
… view tools

Changes proposed in this pull request:
 - add OutputDebugStringW() to print debug info, which can be monitored in dbgview tools.
 - 
 - 

Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

-

### CODE REVIEW

**Comment by dnobori** [comment]
I don't think it is good to output all console strings to the debug view. Only the outputs from the DebugArgs() function (in Str.c) should be copied to the debug view.


// Display a debug string with arguments
void DebugArgs(char *fmt, va_list args)
{
	// Validate arguments
	if (fmt == NULL)
	{
		return;
	}
	if (g_debug == false)
	{
		return;
	}

	PrintArgs(fmt, args);  <-- It is good to insert the code here.
}

**Comment by tidatida** [comment]
Yes, you are right. The better way is to give a switch in config to on/off detail debug print. What's more ,  a detail document about how to quickly understand , use , test source code, or how to build a SoftEtherVPN  development environment is important for most  SE fans.

**Comment by chipitsine** [comment]
@tidatida , are you still here ?

**Comment by tidatida** [comment]
> @tidatida , are you still here ?

I don't think print too much info is a good idea too, so I think it is time to close this issue.  @chipitsine

**Comment by davidebeatrici** [comment]
No problem.

**Pull request closed without merging**
