### PR TITLE
Change IP structure so that IPv4 addresses are stored in RFC3493 format

### PR DESCRIPTION
**Pull request by davidebeatrici**
In addition to saving 4 bytes for each instantiation, this change makes IP-related operations faster and clearer.

https://tools.ietf.org/html/rfc3493.html#section-3.7

### CODE REVIEW

**Comment by paulmenzel** [comment]
The change looks good. Did you benchmark, that it’s faster now?

PS: The CI Ubuntu build failed with

    configure: error: No compatible LZ4 compression library found. Consider --disable-lz4
    + exit 1

**Comment by chipitsine** [comment]
CI fails, it is known, but harmless. I will fix this week.

**Review by chipitsine — APPROVED** [review]

**Comment by davidebeatrici** [comment]
> The change looks good. Did you benchmark, that it’s faster now?

I actually didn't, but I wouldn't expect noticeable improvements in terms of throughput from this change alone.

However, there is definitely a lot of space for improvements.

**Comment by davidebeatrici** [comment]
Looks like the macOS CI build is not starting, I'm going to merge the PR anyway as I already know that it succeeds.

**Pull request merged**
