### PR TITLE
Add IPv6 route management for Windows client

### PR DESCRIPTION
**Pull request by domosekai**
SoftEther Windows client has these route management functions for IPv4.
- Add static routes to the server address and static DNS server (if any)
- Remove default routes other than the VPN's (and add back later)
- Fix routing issues if the default route is PPP

This PR uses the new API that supports IPv6. The new API is available since Vista.

As more and more VPN tunnels start to support IPv6, without this fix we must perform manual adjustment on the routing table, e.g. in order to prevent VPN connections get cut off due to new default route pushed from the tunnel.

After this fix, the option `NoIPv6DefaultRouterInRAWhenIPv6` can be safely set to `false` for Windows clients.
See #1163 

---

Changes proposed in this pull request:
 - Add IPv6 route management for Windows client
 - Remove obsolete Win32 calls
 - Fix IPv6 leak in dual-stack client if only IPv4 default route is added

### CODE REVIEW

**Comment by domosekai** [comment]
Reviews are welcome.

**Comment by chipitsine** [comment]
I do not think we'll get many reviews.
should be ok to merge to master, thus more people will test :)

**Comment by metalefty** [comment]
I've wanted this feature. Thanks you!

> should be ok to merge to master, thus more people will test :)

Built Windows client binaries should be created to get more tests by many people.
I'm also the one who are not familiar with creating Windows binaries and cannot create Windows client binaies by my own.

**Comment by chipitsine** [comment]
@metalefty , you can download artifacts from Azure Pipeline: https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build/results?buildId=632&view=logs&jobId=b9e62f99-1a98-5ed7-01d2-f4794231ed79

(see "2 artifacts" link)

**Comment by metalefty** [comment]
I see, thanks!

**Comment by domosekai** [comment]
PR artifacts can't be normally uninstalled.

**Comment by domosekai** [comment]
Does anyone know why the client manager does not automatically refresh after connect or disconnect?

**Comment by chipitsine** [comment]
I recall using installer from artifacts. I was able to uninstall.
but we should recheck if there are bugs

**Comment by domosekai** [comment]
From nightly builds, you can uninstall. But not from PR.

**Comment by chipitsine** [comment]
Interesting

**Comment by domosekai** [comment]
It seems the only thing different between nightly builds and PR builds is BUILD_NUMBER.

**Comment by davidebeatrici** [comment]
I'm working on an MSI installer anyway (#195).

> Does anyone know why the client manager does not automatically refresh after connect or disconnect?

In #1295 I added `CmRefresh()` calls because I mistakenly thought the issue was only with NIC-related operations (e.g. driver installation).

It looks like, instead, something is broken.

**Comment by domosekai** [comment]
Build number set to 0 will cause failure in loading setuplog.dat.
https://github.com/SoftEtherVPN/SoftEtherVPN/blob/192083e7c46ccf8155238eecccd222cad6c94d38/src/Cedar/SW.c#L4006-L4011

**Comment by davidebeatrici** [comment]
Let's remove that code.

**Comment by domosekai** [comment]
Rebased onto master

**Comment by domosekai** [comment]
Let's merge and see.
Fix #1163

**Comment by domosekai** [comment]
Merge and see if there are comments

**Pull request merged**
