### PR TITLE
Added armv5tel for debian/rules and made pushed routes work correct with OpenVPN

### PR DESCRIPTION
**Pull request by dglushenok**
Armv5tel is for building Debian package on SheevaPlug.
Also, static routes not working properly with OpenVPN as gateway address gets replaced by vpn_gateway. So, you cannot direct all traffic to VPN and make some nets to go through net_gateway.
By the way, even with this fix you have to specify IP address as gateway in config file and cannot use openvpn's vpn_gateway and net_gateway keywords.

### CODE REVIEW

**Comment by dnobori** [comment]
Your great patch is much appreciated. We are considering to apply your patch into the SoftEther VPN main tree.

SoftEther VPN Patch Acceptance Policy:
http://www.softether.org/5-download/src/9.patch

You have two options which are described on the above policy.
Could you please choose either option 1 or 2, and specify it clearly on the reply?

**Comment by dglushenok** [comment]
Hi,

Option 1.

--
Дмитрий Глушенок

**Comment by paskal** [comment]
@dglushenok, after latest merges there are conflicts, could you please fix your patch?

**Comment by dnobori** [comment]
Thank you so much for your contribution to enrich the SoftEther VPN source code.

Your patch has been merged on the main source-tree of SoftEther VPN.

As a token of our gratitude, your GitHub username has been added on the AUTHORS.TXT file and on the header of the related source file.
Please see: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/AUTHORS.TXT

Thanks again for your contribution.

**Pull request merged**
