### PR TITLE
Incorrect variable used while iterating through sessions which makes the loop stuck

### LINKED ISSUE #2043: 100% core loading related to IPSEC/L2TP issued by AMajor-C
### Are you using SoftEther VPN 5.x?

- [X] Yes, I'm using SoftEther VPN 5.x, not 4.x.

### Version

_No response_

### Component

VPN Server

### Operating system & version

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### Architecture or Hardware model

_No response_

### Steps to reproduce

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

Refer to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854

### Anything else?

As to https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1854
This case has been left alone for a long time.

This case should be resolved by the person who changed the source code (the person concerned).

Source code change made by Evengard.
https://github.com/SoftEtherVPN/SoftEtherVPN/commit/1bdd9a92bcd97b55d0863a01202d872e16c4b32d

Source code:
PROTO_L2TP C_2024-08-19

### PR DESCRIPTION
**Pull request by Evengard**
Should fix #2043 
Now there may be another reason for it being stuck elsewhere, but I just did the thing which should had been done a long time ago, my bad

### CODE REVIEW

**Comment by chipitsine** [comment]
@AMajor-C

can you please check this fix, it is likely addresses the issue you reported

**Comment by Evengard** [comment]
Running this fix on my vpn server which actually got stuck with the same problem sometimes before, without problems so far for now

**Comment by chipitsine** [comment]
oops, I accidently released without merging of this PR.
ok, today will be two releases

**Comment by chipitsine** [comment]
released: https://github.com/SoftEtherVPN/SoftEtherVPN/releases/tag/5.02.5187

**Pull request merged**
