### PR TITLE
Create openvpn_sample.ovpn

### PR DESCRIPTION
**Pull request by Hope4hope**
safer connection

### CODE REVIEW

**Comment by moatazelmasry2** [comment]
Hi there. I agree on the choice of the cipher, but not on the auth hash. I'd personally like to have SHA256 as the default auth because it is more standard and offers almost same speed.
Also could you please resolve the conflict in the pull request?

**Comment by moatazelmasry2** [comment]
Hi @Hope4hope could you please update your PR according to:
https://github.com/SoftEtherVPN/SoftEtherVPN/pull/330#issuecomment-339487751

**Comment by moatazelmasry2** [comment]
@Hope4hope Ping!!!

**Comment by chipitsine** [comment]
@Hope4hope , are you here ?

**Comment by davidebeatrici** [comment]
Closing for lack of activity, feel free to reopen.

**Pull request closed without merging**
