### PR TITLE
Added ListenIP to server configuration

### PR DESCRIPTION
**Pull request by maikelohcfg**
SofEtherVPN now can be binded to specific IP address, by default it listen in 0.0.0.0. 

In server configuration, section ServerConfiguration will find parameter ListenIP. 

This work is based on macvk, almost two year without news about him and i thinks this feature is very important to the project to be forgotten, thanks macvk.

### CODE REVIEW

**Comment by aenertia** [comment]
Does this work for V6 interfaces as well?

More importantly can the Administrative login be bound to a specific IP
whilst others are not?

**Comment by maikelohcfg** [comment]
Ipv4 only for now, later i can try ipv6

**Comment by macvk** [comment]
this option is already added two years ago. see here for details https://github.com/SoftEtherVPN/SoftEtherVPN/pull/202

**Comment by macvk** [comment]
please stop copy-paste my code. this looks like plagiarism and this is plagiarism

**Comment by maikelohcfg** [comment]
macvk sorry the miss understanding if you see my pull request note i always mentioned this your job
"This work is based on macvk, almost two year without news about him and i thinks this feature is very important to the project to be forgotten, thanks macvk." 
as i wrote two years has past without any news from you i dont want credit for this, all the credit is for you. i dont want plagiarize your job at all.

**Comment by macvk** [comment]
maikelohcfg right solution for that conflict is DELETING "your code" from repository and leave my code.

**Comment by maikelohcfg** [comment]
Seriusly i dont expect this will make you so upset, because i always say this is your job, but i will not explain me anymore. For the good sake of the community i will close my repository  but i will like that you dont wait two years more for reply a question that allowed to merge your code in important projects like this making think every one that you are not Interested in that code. For me is end of toppic.

**Comment by aenertia** [comment]
The right way to do this is to form the Repo from GitHub. Then create a new
fork of your own then create a all in one patch on your branch from The
original one. Then submit the all in one patch as a pull request to
upstream. This will keep the originators commit logs and author intact and
you can submit it as a pull request.

On 25 Aug. 2017 11:26 pm, "Maikel Ortega Hernández" <
notifications@github.com> wrote:

Closed #331 <https://github.com/SoftEtherVPN/SoftEtherVPN/pull/331>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SoftEtherVPN/SoftEtherVPN/pull/331#event-1221568842>,
or mute the thread

**Comment by maikelohcfg** [comment]
> The right way to do this is to form the Repo from GitHub. Then create a new
fork of your own then create a all in one patch on your branch from The
original one. Then submit the all in one patch as a pull request to
upstream. This will keep the originators commit logs and author intact and
you can submit it as a pull request.

thanks i will have in mind for future.

**Pull request closed without merging**
